### ISSUE TITLE
Authenticated users could NOT edit their own sessions

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2015#1]
OOTB sessions are not editable by the submitter because all sessions get associated with the default conference (OG) which no one is a member of. Even if you were a member of the OG, the OG permissions OOTB don't come configured for any extra permissions. So even though the global permission for "edit own session" is set to allow an authenticated user to edit their own session, they ultimately cannot.

**Comment by Nneka** [comment]
I personally had this problem.  Once I submittted my session, I could not edit it.  Will have this tested by our meeting this Saturday.

**Comment by timwood** [comment]
I've just tested this from my a regular "authenticated user" account (the one Nneka created for me) and I do not have permission to edit my own session. It has to do with the Organic Group the session node is associated with. The regular user is not a member of the organic group and thus restricted from editing their own node. I need to do more testing to find out whether a user with a ticket to an event that went through a normal registration process, becomes a member of the group. Or whether we need to change the permissions.

**Comment by timwood** [comment]
I've narrowed it down to two options to "fix" this issue. I'm waiting to hear back from either Dave Stoline or Matt Connerton.
1. Change the active conference's permissions (OG perms) to allow non-members to "edit own" sessions and bof-sessions. OR change the default OG perms in the same way.
2. Change the global OG setting "Strict node access permissions" (og_node_access_strict), currently CHECKED, at /admin/config/group/settings. I'm not sure whether there are any other implications of changing this, but it's the option I'm leaning toward.

**Comment by timwood** [comment]
I decided to go with option #2. I used features_override to export and override the og_node_access_strict variable in the cod_events feature.

Now authenticated users can edit their own sessions and bof-sessions.
