### ISSUE TITLE
Add Sprints menu item to Community menu 

### ISSUE THREAD

**Issue by bendygirl** [Drupal4Gov/Drupal-GovCon-2015#100]
@timwood @jonraedeke @Nneka 
Need to add a new menu item for Sprints.
I'll need to add content and link to a googledoc where Kalpana is managing the list of D8 sprinters. 

This is a new requirement, but moving forward, pretty important that we get this up and working. I'll add a link to the googledoc when I have it. 

I figure you 3 are the most likely to do this.

**Comment by timwood** [comment]
So a simple content page with info about sprints and link to the gdoc? Any
admin can create that and make the menu item under community. If linking
directly to the gdoc from the menu, we can do that too.

**Comment by bendygirl** [comment]
Right now this is more of a holding spot for how we want to do this.

We could use an iframe for the page and link the document that way, but I'm asking Kalpana what would work best for her since she's gonna run the sprints. 

I suspect it'll be a simple menu item with a link to the googledoc and then some theming (might not even need theming). Just waiting now for the googledoc, just don't want to make a final decision until we have that and have Kalpana's take on what's easiest for her.

**Comment by bendygirl** [comment]
@timwood Kalpana suggested a menu link. So, I can do this, should I do it on dev? Link to the  document https://docs.google.com/spreadsheets/d/1zbhJoz1KkHmaN0JOQXb_-0dvR010fUzvYc_jfHRJ7yg/edit#gid=0

I'm going to add content from here https://groups.drupal.org/node/463288 to a news piece and I think probably use some of it also on a page.

**Comment by timwood** [comment]
Since a menu item is just content I'd just add it right to the production environment/site. Please feel free to do it yourself, if you have time. I suggest appending "(Gdoc)" to the link text and/or title tag attribute for the menu item so it's clear the link leaves the site.
