### ISSUE TITLE
How do we setup a "/live" feed for keynotes

### ISSUE THREAD

**Issue by cmndr-king** [Drupal4Gov/Drupal-GovCon-2015#102]
We will live stream the three keynote sessions using a service offered by NIH.  Here's the home page:

http://videocast.nih.gov/

If you go to that link, you can pull up upcoming and past sessions to see to what degree it can be embedded.  As soon as our sessions have been finalized and added to the calendar, I can update the ticket.

**Comment by timwood** [comment]
I've got an unpublished page up with an example embed from the NIH videocast. Seems to work, even replacing http with http**s**. Would like to ask @jonraedeke whether we can do anything to make this responsive.

https://www.drupalgovcon.org/drupal-govcon-2015/drupal-govcon-2015-live

**Comment by timwood** [comment]
The links for the live stream for the three keynote addresses are:

Wednesday - http://videocast.nih.gov/summary.asp?live=16473

Thursday - http://videocast.nih.gov/summary.asp?live=16475

Friday - http://videocast.nih.gov/summary.asp?live=16477

**Comment by timwood** [comment]
@cmndr-king Do you know if we can just change the "file" parameter in the embed code I used in the example page to one of the numbers in the live links above? Here is the code I used:

``` html
<iframe frameborder="0" height="411" src="https://videocast.nih.gov/embed.asp?file=19039&amp;w=640&amp;h=360" width="645">browser does not support iframe</iframe>
```

**Comment by cmndr-king** [comment]
I finally go the final links for the live feeds.  Here's the message from them but it looks like the easy route would be to simply link to the main page which will work each of the days.  After that, the other links will eventually point to the recording (there could be a delay):

The preferred link for any event is http://videocast.nih.gov
This will display “today’s” events and handle all the automation.  That is what I would put on your website.

However, if you must have direct links to each specific event, they are:

Day 1: http://videocast.nih.gov/live.asp?live=16473
Day 2: http://videocast.nih.gov/live.asp?live=16475
Day 3: http://videocast.nih.gov/live.asp?live=16477

**Comment by timwood** [comment]
I've added a "Live!" link to the main menu (far right for non-Admins) which goes directly to the NIH videocast page. No sense in having a content page which just links to a single other site.
