### ISSUE TITLE
Can we add the program schedule onto the program page?

### ISSUE THREAD

**Issue by cmndr-king** [Drupal4Gov/Drupal-GovCon-2015#103]
This page:

https://www.drupalgovcon.org/drupal-govcon-2015/upcoming_program

says that the schedule will be posted in April.  I was assuming something like:

10-11am - Opening Keynote
11-11:15 - Break
11:15-12 - Breakout session 1
etc.

**Comment by timwood** [comment]
I believe this was intended to be a temporary solution until sessions were selected, right @cmndr-king ? Or is it to compliment the built-in COD functionality as a more high-level overview schedule for the event?

**Comment by cmndr-king** [comment]
Primarily a filler. It could be useful to show the entire schedule at a glance but not critical if we have a mobile friendly full schedule.

-James

---

James King, MLS, FSLA

http://about.me/cmndr_king

On Jun 6, 2015, at 5:22 PM, Tim Wood <notifications@github.com<mailto:notifications@github.com>> wrote:

I believe this was intended to be a temporary solution until sessions were selected, right @cmndr-kinghttps://github.com/cmndr-king ? Or is it to compliment the built-in COD functionality as a more high-level overview schedule for the event?

**Comment by timwood** [comment]
@cmndr-king If it's not too much work, can you add a manually added, text-based (using headers similar to https://events.drupal.org/losangeles2015/program) to the upcoming program page linked in this task? Then change the path to just program (remove upcoming_).

**Comment by timwood** [comment]
Done!
