### ISSUE TITLE
Can't edit the Program page to change announcement

### ISSUE THREAD

**Issue by cmndr-king** [Drupal4Gov/Drupal-GovCon-2015#104]
We need to remove the "submit a session" option and change release date to end of May.

https://www.drupalgovcon.org/drupal-govcon-2015/upcoming_program

**Comment by bendygirl** [comment]
done.

**Comment by cmndr-king** [comment]
Not so fast partner - I get this message when trying to edit.
![screenshot](https://cloud.githubusercontent.com/assets/11525049/7778484/10845800-009a-11e5-815e-78c0ca013b5b.png)

**Comment by bendygirl** [comment]
Thanks James. You're a "content editor" and this is a known issue.
https://github.com/Drupal4Gov/Drupal-GovCon-2015/issues/63
I can give you admin if that's okay with @timwood but right now, it's the only work around we have.

**Comment by cmndr-king** [comment]
No problem, I don’t need admin and can wait.

-James

---

James King, MLS, FSLA

http://about.me/cmndr_king

**Comment by bendygirl** [comment]
if you do, let @timwood or me know and happy to help.
