### ISSUE TITLE
Theme the session schedule

### ISSUE THREAD

**Issue by jonraedeke** [Drupal4Gov/Drupal-GovCon-2015#111]
I like https://austin2014.drupal.org/schedule.html

I'm probably going to create a new view for this instead of trying the overwrite what COD did.

**Comment by jonraedeke** [comment]
Decided to forgo the ability to filter by session track so I was able to just override the COD session schedule. TODO: styling

**Comment by jonraedeke** [comment]
Just committed the styling to dev.

![screen shot 2015-06-10 at 1 24 47 pm](https://cloud.githubusercontent.com/assets/2054715/8089337/4ccc0f80-0f75-11e5-8592-0896ea1a76e3.png)

**Comment by timwood** [comment]
Looks awesome! Only thing I noticed is that the "Front-end, User Experience and Design" track is too long and bleeds into the track on the next line. It's not very noticeable on desktop, but is much worse on other break points.

![screen shot 2015-06-10 at 2 13 43 pm](https://cloud.githubusercontent.com/assets/91050/8090333/621cbc80-0f7b-11e5-927a-836853df55b6.png)

![screen shot 2015-06-10 at 2 17 33 pm](https://cloud.githubusercontent.com/assets/91050/8090355/822449c6-0f7b-11e5-928a-1240e4a65849.png)

Also, would it be difficult to add AJAX filters to the view for Track and level?

**Comment by jonraedeke** [comment]
Oops, I'll fix that. There's always gotta be one super long title. Front-End, UX and Design would have been good.

Yes, it's very hard to add filters the way this view is set up. Filtering a view of aggregated time slots on one session term just isn't working for me. AJAX filter might be impossible.

I'm open to suggestions.

**Comment by jonraedeke** [comment]
Might have to totally redo the view like you did with the sessions view and not use AJAX tabs for the days to get filters to work.

**Comment by timwood** [comment]
So I was able to get an exposed filter to work against all the embedded views by adding an additional page display to "COD Event Sessions" view and enabling the "Exposed form in block" setting. Then I added that block to the panel above the view. It filters all the views of sessions in all the timeslots and across the days. I also had to add a relationship to "COD Event Sessions" view to make the exposed filter a select list of Session Track term names. 

The only thing is the filter appear above the whole view and not in between the days and timeslots, which would be ideal. I could not come up with a way to have it appear where I wanted it. Maybe we could do that with CSS? Should I save the changes I made to the view and push out?

![screen shot 2015-06-10 at 3 50 44 pm](https://cloud.githubusercontent.com/assets/91050/8092716/b8744662-0f89-11e5-92fe-85a3a9c27f0c.png)

**Comment by jonraedeke** [comment]
Man, you're good! I say it's perfect. I think I can move it with css after it's in code.

**Comment by timwood** [comment]
Changes committed and pushed to Git develop branch.

**Comment by timwood** [comment]
This is done!
