### ISSUE TITLE
Broken link to sessions from Program page

### ISSUE THREAD

**Issue by alisonjo315** [Drupal4Gov/Drupal-GovCon-2015#113]
At the bottom of https://www.drupalgovcon.org/drupal-govcon-2015/upcoming_program

Link to accepted sessions goes to https://www.drupalgovcon.org/drupal-govcon-2015/sessions
# wompwomp

I can just update the link, or is there a desire to change how the view behaves (or both)? ( @timwood @jonraedeke )

**Comment by timwood** [comment]
The view behaves how we want it now. I thought I had put the correct link in when I edited that page the other day, but I guess I didn't. :-( Feel free to update to append /accepted and it will work!

**Comment by alisonjo315** [comment]
K, all done, thanks!
