### ISSUE TITLE
Codify session views change that hides keynotes

### ISSUE THREAD

**Issue by jonraedeke** [Drupal4Gov/Drupal-GovCon-2015#114]
So the keynotes added were showing up on the homepage in the listing of sessions and the icon links. I think it's best to hide them here, but show on schedule view. I did it in production, since it was breaking the nice 4-up icon links on the homepage.

**Comment by jdearie** [comment]
good call - thx Jon! I hadn't even thought to look at the accepted sessions page.

**Comment by timwood** [comment]
I'll take care of this now.

**Comment by jonraedeke** [comment]
Thanks!

**Comment by timwood** [comment]
Just pushed code changes.
