### ISSUE TITLE
Images in Basic Pages

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2015#117]
When attempting to add an image to a basic page, there's no upload option... heard there was a work-around for news articles with the same issue?  @timwood ?

**Comment by timwood** [comment]
@jdearie Sorry for the delay. You don't see the File attachments field on basic page?
<img width="573" alt="screen shot 2015-07-08 at 9 11 18 pm" src="https://cloud.githubusercontent.com/assets/91050/8585862/f1ae1f24-25b5-11e5-8bcb-707a375522ae.png">

**Comment by jdearie** [comment]
I do - but I was trying to put images inline - screenshots of some of the steps...

**Comment by timwood** [comment]
Since COD doesn't come with image to WYSIWYG convenience buttons/functionality, I guess you'd just have to get the URL of the uploaded image and manually add it to the body.

**Comment by jdearie** [comment]
ok - good to know. thx.
