### ISSUE TITLE
BoF 

### ISSUE THREAD

**Issue by bendygirl** [Drupal4Gov/Drupal-GovCon-2015#119]
Need to:
- [ ] test (do these work? Who can add? How do you add? Rooms? Scheduling? Preventing Spam?)
- [x] Expose for users to create BoF
- [x] Allow a schedule to be created for scheduled BoFs
- [x] Theme BoF Schedule

May need to break these down into different tasks but putting them all together for right now.

**Comment by bendygirl** [comment]
@Nneka @timwood @jonraedeke @onelittlebecca 

just making sure you all see this new item.

**Comment by Nneka** [comment]
BOF functionality does work. Tested this functionality on the dev environment.  To enable BOF scheduling for a session time, use the scheduling page -->  admin/conference/1/schedule.
![screen shot 2015-06-28 at 2 57 10 pm](https://cloud.githubusercontent.com/assets/1054114/8397750/8c77e630-1da4-11e5-88ce-9f9751f44403.png)

Click on 'Edit timeslots'.  Under the 'Allowed Types', select BOF.  This will need to be done for each time/room that is needed for BOF's.   Once this is done, you can return back to the individual BOF node and select the correct date and time.

In order to expose users to the BoF's, you will have to ensure authenticated users have the ability to create a BoF.

Investigating #3 - Allowing a schedule to be created for scheduled BoFs.

**Comment by Nneka** [comment]
@bendygirl 
The page that displays scheduled BOF's can be viewed here -->  http://capitalcampdev.prod.acquia-sites.com/node/1/bofs .  

It definitely needs some improvement on the theme if it will be used.  It first groups the BOF's by days.. and within that day it groups them by room and time.  

The functionality is there, just needs to be tweaked a little.  

What are the next steps?

**Comment by timwood** [comment]
Looks like this is also on the production site here: https://www.drupalgovcon.org/drupal-govcon-2015/bofs where there's already some dates/timeslots which have been enabled for BOFs (probably not the right ones)

**Comment by bendygirl** [comment]
So, as @timwood suspected, not the right ones. Forgot to also add @Nneka 

I created 3 BoFs. Also made each Room and timeslot a BoF as needed.

No luck.

I added 3 BoFs, but, there's a problem.

I can't associate the schedule with the BoF I just created. Open the BoF, can't add the room or Time. 

Really could use this, folks won't sign up during the event. Past few years, no one does. We have to do this online if they're going to do it.

**Comment by bendygirl** [comment]
@timwood @Nneka It's working now. I think it's @jonraedeke, but he says he didn't do anything.

But the schedule option is there, collapsed, but it's totally there. The three new BoFs I added are now also plotted.

**Comment by jonraedeke** [comment]
I pushed styling and views overrides for date and time formats to dev. It looks like this now.

![screen shot 2015-07-11 at 1 38 59 pm](https://cloud.githubusercontent.com/assets/2054715/8635001/afc6c978-27de-11e5-8c84-18449e6422ea.png)

![screen shot 2015-07-11 at 1 39 14 pm](https://cloud.githubusercontent.com/assets/2054715/8635002/bc19adee-27de-11e5-8be8-4e3dcb350ae6.png)

**Comment by bendygirl** [comment]
Jon, those look great!

**Comment by timwood** [comment]
So @Nneka and @jonraedeke Is there anything left to do for this to work for our attendees? Did someone test the ability of a normal logged in user to create a BoF? Is there a permission change needed? What about scheduled times, do we need to add those so people can schedule BoFs for the rooms/times allowed/available?

**Comment by jonraedeke** [comment]
@timwood Looks like you are required to log in to schedule a BoF. The help text on the that page says to log in. When not logged in, you see the scheduled BoFs but not the button. Seems fine. Good to go as far as I can tell.

**Comment by jonraedeke** [comment]
@timwood I suppose similar help text would be good on the "My Schedule" page, but that may seem obvious.

**Comment by timwood** [comment]
Yeah, I thought about adding it, but decided not to.

**Comment by timwood** [comment]
Bofs are up. Let me know if something doesn't work. Thanks all for help on this one!

**Comment by bendygirl** [comment]
when creating a BoF, the "create a BoF" button doesn't go away after a BoF is created.

Should be able to limit this to one BoF per available room.

**Comment by bendygirl** [comment]
![bof](https://cloud.githubusercontent.com/assets/956933/8678708/00bd2ba0-2a24-11e5-8b43-e97e8b055154.png)

**Comment by bendygirl** [comment]
BoF doesn't allow you to add to your schedule, but the flag is enabled.

**Comment by timwood** [comment]
It's just that there is no button (flag is not displayed) on the BoF schedule view, BoF node display, etc., so it cannot be added to schedule due to that. I left it out because I was lazy and tired. If we add it, we may need to tweak the "My Schedule" view.

**Comment by bendygirl** [comment]
We need to disable the "create" BoF once the room has a BoF scheduled. 

We've got an over lap on thursday where this has happened.

https://www.drupalgovcon.org/drupal-govcon-2015/bofs
![two bofs same roomo](https://cloud.githubusercontent.com/assets/956933/8753156/5a260634-2c87-11e5-9728-d09907cca86d.jpg)

**Comment by timwood** [comment]
@bendygirl I'm not sure how to accomplish that. Any ideas?

**Comment by timwood** [comment]
BoF's are now able to be added to "my schedule" and show there and you can only add one BoF to a timeslot. These changes are NOT yet live on DGC.org. They should be by tomorrow.

**Comment by bendygirl** [comment]
on staging?

On Fri, Jul 17, 2015 at 11:50 PM, Tim Wood notifications@github.com wrote:

> BoF's are now able to be added to "my schedule" and show there and you can
> only add one BoF to a timeslot. These changes are NOT yet live on DGC.org.
> They should be by tomorrow.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Drupal4Gov/Drupal-GovCon-2015/issues/119#issuecomment-122479881
> .

## 

Kirsten
http://uniongal.blogspot.com
Join Uniongal on Reddit http://www.reddit.com/r/Uniongal/

**Comment by timwood** [comment]
Not on staging yet.
