### ISSUE TITLE
Accessibility page needs updates

### ISSUE THREAD

**Issue by cmndr-king** [Drupal4Gov/Drupal-GovCon-2015#122]
There are a number of typos on the accessibility page and I don't have the rights to save the change.  In addition, I can provide additional specifics on what accommodations are available.

Here's the proposed text:

The Drupal GovCon team is committed to providing a rewarding experience to all our attendees. If you require any assistive technology or other accommodations, please let us know [link to https://www.drupalgovcon.org/drupal-govcon-2015/contact-us]. We will do our very best to accommodate all requests. 

The NIH campus, including the security building, campus shuttles, and the Natcher Conference Center (Building 45) are all wheelchair accessible.  [NIH Building Accessibility Maps] [link to http://www.ors.od.nih.gov/maps/accessibility/Pages/se_section.aspx]

In preparation for the 2015 Drupal GovCon, the following accommodations have already been arranged:

• Sign Language interpreters will be available at the keynote sessions
• Headsets are available in the Natcher auditorium upon request
• The three keynote sessions will be live streamed, with live captioning, in the balconies and on the open web.

We also have the following additional services available upon advanced request:
• Sign language interpreters in breakout session
• CART (Computer-Aided Realtime Translation)

If you need any of these additional services or require assistance beyond what is listed, please contact us at least two weeks before the conference. [link to https://www.drupalgovcon.org/drupal-govcon-2015/contact-us]

Read more about the NIH Interpreting Services here [http://www.ors.od.nih.gov/pes/dats/interpret/Pages/index.aspx]

**Comment by bendygirl** [comment]
should be done @cmndr-king check it please.

**Comment by cmndr-king** [comment]
You have some literal text in there that should be removed.  For example, I said [link to …) and that text is still in there.  I added those notes because the ticket stripped out HTML.

-James

---

James King, MLS, FSLA

http://about.me/cmndr_king

**Comment by bendygirl** [comment]
updated

**Comment by cmndr-king** [comment]
Awesome, thanks!

-James

---

James King, MLS, FSLA

http://about.me/cmndr_king
