### ISSUE TITLE
Waitlist solution

### ISSUE THREAD

**Issue by timwood** [Drupal4Gov/Drupal-GovCon-2015#123]
Featurize:
- [x] Changes to ticket registrations view to expose filter by state,
- [x] and VBO operation to change ticket state
- [x] New rule for waitlist thank you redirect on registration
- [x] New rule for emailing waitlist ticket holder when their ticket is approved (and corresponding component to accomplish this)
- [x] Change CSS and DGC 2015 home page panel to link the big ticket graphic to drupal-govcon-2015/registration again and change wording to "Waitlist"

Live site:
- [x] Manually revert view (at https://www.drupalgovcon.org/admin/structure/views/view/ticket_registration/revert)
- [x] Set end date for "Free ticket" type to yesterday.
- [x] Add waitlist thank you content page (at path drupal-govcon-2015/waitlist-thank-you)
  - Title: Waitlist thank you
  - Body: (copy "want more info" content from existing thank you page)

``` HTML
<p>You are on the waitlist! We'll notify you if a ticket opens up.</p>

<p>Soon, you will receive an email to complete your account activation.</p>
```
- [x] Add new ticket type (at https://www.drupalgovcon.org/admin/conference/1/edit)
  - Type: Waitlist
  - Start date: today
  - End date: 7/20
  - Quantity: 100
  - Min/Max per order: 1
  - Default ticket state: Pending
  - Description:

``` HTML
<p>Tickets to the event are sold out, but we are starting a wait list.&nbsp;Please register (only one wait list ticket per registrant)&nbsp;to get on the wait list. If you already have a Free ticket, please don't register for the waitlist, you can check whether you already have a ticket by logging in and coming back to this page.&nbsp;If you are on the wait list, you are NOT guaranteed a ticket to the event. If you don't already have one, you will create a new account as part of the registration process.</p>

<p><strong>A new account is required even if you've attended previous CapitalCamp or Drupal Gov Days before.</strong></p>

```
- [x] Manage ticket fields for new ticket type (at https://www.drupalgovcon.org//ticket_registration/manage/2/fields) to copy "Dietary needs", ~~"T-shirt size"~~ and "Government Employee" from user fields, inbetween Last name and Flags and ordered as above to match original, free ticket type.
- [x] Set "Dietary needs" and ~~"T-shirt size"~~ fields on new ticket type to REQUIRED.
- [x] Change "Tickets" user menu item to "Waitlist" (at https://www.drupalgovcon.org/admin/structure/menu/item/9266/edit)
- [x] Manually revert rules

**Comment by timwood** [comment]
Was reminded we don't have a t-shirt sponsor so no need for t-shirt fields anymore. Will not add to new ticket type, but won't remove from User or original "Free ticket" type.

**Comment by jonraedeke** [comment]
Testing this locally.

**Comment by jonraedeke** [comment]
@timwood This works great! The only thing I think needs to change is the email verbiage. I got an email that states "You've been registered for Drupal GovCon and have secured a ticket to the
event." Should be:
"You've been registered as a user on the Drupal GovCon site and have been added to the waitlist for the
event."

**Comment by jonraedeke** [comment]
My bad. After reverting my env, the correct email language was sent. Great job @timwood !

**Comment by jonraedeke** [comment]
@timwood I fixed the big homepage ticket button to say Waitlist and link to the registration page. Also, I figured out all-purpose css that will work with "Tickets", "Sold Out" or "Waitlist".

**Comment by timwood** [comment]
> Manually revert view (at https://www.drupalgovcon.org/admin/structure/views/view/ticket_registration/revert)

Need to look into this more.

**Comment by timwood** [comment]
After reverting the Ticket registrations view I had to manually set the field order again, which is an old bug.
