### ISSUE TITLE
Attendee custom schedule

### ISSUE THREAD

**Issue by timwood** [Drupal4Gov/Drupal-GovCon-2015#124]
Look into how to enable customized schedules for attendees.

**Comment by timwood** [comment]
Custom schedule flag is available and bundled with COD but permissions limit use to Admin role. Additionally, the link doesn't display in the existing "links" object on the session node panel pane. Actually, no links display there. Not sure why. 

Can manually add the flag object as a panel pane on the session panel via Entity > Flag for Node.

One option would be to have it as a link in the top right as seen here:
<img width="1071" alt="screen shot 2015-07-09 at 11 42 05 pm" src="https://cloud.githubusercontent.com/assets/91050/8611786/47ab6e16-2694-11e5-8016-376b42a40a88.png">

Might also be convenient to add from global site Schedule page and Accepted sessions list/grid.
When added to Schedule page it would need some styling help:
<img width="1106" alt="screen shot 2015-07-09 at 11 53 08 pm" src="https://cloud.githubusercontent.com/assets/91050/8611890/05e5934c-2696-11e5-8c19-67559a25308b.png">

When added to Sessions grid it looks good:
<img width="726" alt="screen shot 2015-07-09 at 11 47 30 pm" src="https://cloud.githubusercontent.com/assets/91050/8611817/f2af89e6-2694-11e5-9512-4f5367deaeb8.png">

We could even include a count of how many attendees have flagged each session:
<img width="1068" alt="screen shot 2015-07-10 at 12 00 31 am" src="https://cloud.githubusercontent.com/assets/91050/8611942/bd2cf022-2696-11e5-8d06-17562817230e.png">

Unfortunately COD's default way to view your custom schedule is via a url under the massively ugly Program functionality here: https://www.drupalgovcon.org/drupal-govcon-2015/program/mine and ends up looking like this:
<img width="1128" alt="screen shot 2015-07-10 at 12 06 27 am" src="https://cloud.githubusercontent.com/assets/91050/8612020/dabb5da8-2697-11e5-9a26-3ebdf2a373a5.png">

Thoughts @bendygirl @jdearie @jonraedeke @cmndr-king @dsheffler

**Comment by onelittlebecca** [comment]
I like what you did w adding it to the grid and stuff but I agree the my schedule sessions view/page is ugly and not really overly uhhhh pretty for attendees. 

I do think it is a functionality we need but yea. There. My two cents. 

Becca

Typed by thumbs

**Comment by jonraedeke** [comment]
This is great! Is there a way we could clone the global schedule view we are using and filter by current user's flag?

**Comment by bendygirl** [comment]
Keep in mind our goal in doing this is about overflow. If we plot something for B that really needs Balcony A, this gives us an option to move things around.

**Comment by timwood** [comment]
Honestly, I don't think we'll get enough participation in this feature, even if we promote it heavily, to determine something like that, @bendygirl.

**Comment by timwood** [comment]
I see it more as a convenience for attendees.

**Comment by dsheffler** [comment]
I've had a lot of people personally request a custom schedule so if we can get it done, I think it could be a nice win for us.

**Comment by timwood** [comment]
I think @jonraedeke's idea about cloning the schedule view is a good one. Only bad thing is it's overly complicated (panel + views within a view using views fields, ick!) so I think it will take a bit of effort to accomplish.

**Comment by cmndr-king** [comment]
I agree that it would be great to have but the real value will be having it as soon as the schedule is released next year.  We can promote this and get it used but I’m not sure if enough will use it in the next week.

I agree that the summary view doesn’t look the best – how does it look on mobile?  For a big conference that I’m involved with, they use sched.org that looks like this (http://www.sla.org/attend/2015-annual-conference/2015-online-planner/) :

[cid:image003.jpg@01D0BAF2.FFC3FA30]

-James

---

James King, MLS, FSLA

http://about.me/cmndr_king

**Comment by timwood** [comment]
sched.org creates a very nice schedule. The recent Federal IT Symposium used it, just not sure how it would integrate (feed data to it) with Drupal and that's certainly a bigger lift than we can accomplish in time for this year.

**Comment by timwood** [comment]
I've created a My Schedule and will export to features today. Jon plans to style tonight and I'll try to release as soon as possible after that.

<img width="610" alt="screen shot 2015-07-13 at 11 48 37 am" src="https://cloud.githubusercontent.com/assets/91050/8654216/ffa84d26-2956-11e5-9467-4e70ba0af06d.png">
<img width="774" alt="screen shot 2015-07-13 at 11 48 52 am" src="https://cloud.githubusercontent.com/assets/91050/8654214/ffa29dc2-2956-11e5-8bba-a912c270587c.png">
<img width="634" alt="screen shot 2015-07-13 at 11 48 23 am" src="https://cloud.githubusercontent.com/assets/91050/8654215/ffa4e9d8-2956-11e5-8cb1-32f27603e97b.png">

**Comment by timwood** [comment]
Custom schedule is live. Let me know if there are issues.
