### ISSUE TITLE
Create second mailchimp sign up and add to sponsors page

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2015#13]

**Comment by jonraedeke** [comment]
I added another Mailchimp list and configured it. I still need to add the form on the splash page.

**Comment by jonraedeke** [comment]
At the last mtg, we decided a sign up form to get the sponsor info was too indirect. The new plan is link to a static sponsor page with the info, prospectus and mailchimp sign up there.

**Comment by timwood** [comment]
Hey @jonraedeke what is the status of this task? @Nneka asked Kirsten for priorities recently and getting up the sponsor information was at the very TOP. Since I don't believe we are anywhere near ready with the new COD site, I think we should still put it up under the static "splash" site as this task outlines. Do you want me to take a stab at it?

**Comment by timwood** [comment]
I've taken a stab at a page. Only half of it is saved in a new file. Most of the style changes/moving stuff around I did in chrome inspector. I've attached a screenshot. I could not find draft content for the sponsors page. Not sure how much language needs to go on there aside from a link to the prospectus and signup form. I purposefully removed the "Drupal govenment days and ..." tape thing at the top to make more room, but I'm sure Jon has something else in mind for how a sub-page like this should look.
![screen shot 2015-02-21 at 1 37 18 pm](https://cloud.githubusercontent.com/assets/91050/6315409/0eed6d5e-b9cf-11e4-89d9-eedf2267c3f3.png)

**Comment by jonraedeke** [comment]
I like it @timwood . I thought we were on hold until the prospectus was finished. Is it ready?

**Comment by timwood** [comment]
I've asked via email whether the prospectus is ready. I see a couple versions in Gdocs.

**Comment by timwood** [comment]
Closing as we've decided to just link to the prospectus PDF directly from the splash home page.
