### ISSUE TITLE
Mailchimp Updates

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2015#133]
Need to:
- [x] import latest list of ticket registrants
- [x] update mailchimp segment to account for volunteers 
- [x] update mailchimp segment to account for organizers
- [x] clean-up/validate speaker list in mailchimp against the site list of speakers.  
- [ ] do this again at some point.

**Comment by jdearie** [comment]
I updated the mailchimp attendee list with the most recent export (7/14/2015 13:56).

I reviewed the Volunteer Google Doc and site Webform and updated individual member profiles to add them to the volunteer segment.

**Comment by jdearie** [comment]
how did @timwood manage to not be in any of our MailChimp lists???

**Comment by timwood** [comment]
I have an email notification about an @comment for me but see that it may have been deleted here. I should be on the Mailchimp list. I've been signed up as an attendee for a while.

**Comment by jdearie** [comment]
I deleted it cuz i found you!  your email was in there but not your name...so when I searched for Tim, I got nothing.. then I found you :)
