### ISSUE TITLE
My schedule link when logged in on mobile devixe

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2015#136]
I was in my phone and followed a Twitter URL to the schedule. Clicked on my schedule. Empty. Oh ok, right. Gotta login. Clicked log in link from top left. Logged in. Used menu to get back to my schedule. Empty again - and login link is telling me to login. Clicked login again - I see my profile. Confirms I'm logged in, right?  Use menu to get back to my schedule and again it's empty and as if I'm not logged in. 

Using Safari on my iPhone. Can someone else test? Hoping this is just me.

**Comment by jonraedeke** [comment]
Just tried myself with Safari on an iPhone. I was able to log in and see "My Schedule" with sessions I previously added.

When you are looking at your schedule do you have the "log out" link in the upper right?

**Comment by jdearie** [comment]
Ok, weird. Everything looks fine now. I swear I tried it 3-5 times to be sure I wasn't missing a step. Guess it was just a fluke.
