### ISSUE TITLE
Provide Matt Connerton with...

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2015#139]
a sanitized database dump (no personal user info needed) of the drupalgovcon site

email matthew@aspiringweb.com

If it's too big, just provide him with instructions on how to get it.

this will help him improve COD development.

**Comment by timwood** [comment]
I think it's important to keep user accounts, at least those which reported issues editing their session nodes, or other bugs. Would it be good enough to sanitize the email addresses and passwords and leave everything else?

**Comment by timwood** [comment]
Dump provided to Matt via private Gdrive share.
