### ISSUE TITLE
Recover video file for session?

### ISSUE THREAD

**Issue by jonraedeke** [Drupal4Gov/Drupal-GovCon-2015#146]
I was contacted directly by the speaker for the following session:
https://www.drupalgovcon.org/drupal-govcon-2015/sessions/phased-migration-drupal-nuts-and-bolts

He closed out the video before he got a chance to save it. He is hoping to recover the AVI file from the temp directory using this info he found:
https://feedback.techsmith.com/techsmith/topics/the_recorded_video_files_location

I don't know if this is too late or if this is reasonable? @cmndr-king

**Comment by cmndr-king** [comment]
I pulled the files from the desktop and documents folders and uploaded them to the recordings folders on Google. If they are not there, I don't have them. I turned in the laptops yesterday and will be on vacation for a well so I can't get it back.

-James

---

James King, MLS, FSLA

http://about.me/cmndr_king

-------- Original message --------

**Comment by jonraedeke** [comment]
No problem, I will let them know. Thanks for all of your time!
