### ISSUE TITLE
Mailchimp and COD integration

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2015#147]
We need to look into connecting the ticket registrations with our mailchimp lists. Right now, the two are completely separate and have to be managed manually. As new tickets were issued, those users weren't added to our mailchimp list unless I manually added or imported them.

We should look into https://www.drupal.org/project/mailchimp

**Comment by timwood** [comment]
This issue was moved to Drupal4Gov/Drupal-GovCon-2016#22
