### ISSUE TITLE
analyze session attendance

### ISSUE THREAD

**Issue by alisonjo315** [Drupal4Gov/Drupal-GovCon-2015#149]
(compare / analyze session attendance vs. the ratings we gave the sessions during session selection -- popularity isn't everything!  but it's something, so let's at least look at it.)

Attendance counts are available in comments on the [volunteer schedule spreadsheet](https://docs.google.com/spreadsheets/d/1aEGKlMD-5EVb-_o63V7axi6MIhluiq_sNCozFfvhMKQ/edit?usp=sharing) (should start by copying attendance counts into a session spreadsheet).

**Comment by alisonjo315** [comment]
I'll aim to do this over the weekend or next week or something.

**Comment by jdearie** [comment]
@alisonjo2786 - did you ever get a chance to do this? If so, where did you post the results?

**Comment by alisonjo315** [comment]
Hmmm I thought you actually did it... I think I went through it but I don't
totally remember. It was in the volunteer spreadsheet, I think, b/c that
was where the attendance info was.  Sorry I'm not being super helpful, work
is still killing me.
