### ISSUE TITLE
Tasks to Make Sure COD Can Do

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2015#15]
- [x] Create time slots by day and by room
- [x] Define times spots as sessions and/or non-sessions (can't remember name COD gave it) 
- [x] Assign sessions and non-sessions to time slots by day --relates to #4 
- [x] Create views of sessions by day and by track
- [x] Can COD successfully do multiple events in one site?

... those are the big ones for now.

**Comment by timwood** [comment]
Here's the list of COD features/functionality I've enabled in my test environment that I will check to see how well they work. Kirsten said all the ones I checked are features we need.

![screen shot 2015-01-18 at 1 17 30 pm](https://cloud.githubusercontent.com/assets/91050/5793749/7ef03d1a-9f1d-11e4-91c4-e5fb5eb5c157.png)

**Comment by timwood** [comment]
> Create views of sessions by day and by track

Based on past Drupalcon sites it should not be a problem to have a list of sessions by day with filters by track or even sessions by track.
