### ISSUE TITLE
Add 2016 dates to DGC homepage

### ISSUE THREAD

**Issue by alisonjo315** [Drupal4Gov/Drupal-GovCon-2015#150]

**Comment by alisonjo315** [comment]
This was mentioned in our group chat -- idk when we want this to happen, and how it should look, or anything else, I just wanted to make a note in here.

**Comment by bendygirl** [comment]
A simple News article would work for now. Would be nice if @jonraedeke could turn the Star for schedule into an icon with the new dates, July 20 - 22, 2016. Same place, same bat time.
