### ISSUE TITLE
Add keynote recording links

### ISSUE THREAD

**Issue by cmndr-king** [Drupal4Gov/Drupal-GovCon-2015#153]
I wasn't sure if we wanted to add it to the bio page of the speaker or add a link to the schedule (or both).

Here are the links to the recordings:

Day 1 - Angie - http://videocast.nih.gov/summary.asp?Live=16473&bhcp=1

Day 2 - Panel - http://videocast.nih.gov/summary.asp?Live=16475&bhcp=1

Day 3 - 3D Printing - http://videocast.nih.gov/summary.asp?Live=16477&bhcp=1

**Comment by bendygirl** [comment]
Done, but the pictures that @jonraedeke had included on the keynote OS panel are no longer showing for me. Not sure what's up with that page. Perhaps the image source is no longer valid?
