### ISSUE TITLE
Get Archive content from 2014 site

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2015#16]
Get content out of old static site so that we can put archived content on the drupal4gov.

**Comment by timwood** [comment]
@jdearie If you run into any trouble downloading the page in it's entirety (once it's available) @sutch has a lot of experience with site scraping.

**Comment by jdearie** [comment]
Listing of sessions that DO have links to presentation material
https://docs.google.com/document/d/1_7AUt5dbN4DY3pSQ7koSUJqBB6HSX0AXVYXnpdtIHkE/edit?usp=sharing

Listing of sessions that DO NOT have links to presentation material
https://docs.google.com/document/d/1RYOi26IbNIJw189W_Y6JdXr-U5w_OEhahg2X6YGDqn8/edit?usp=sharing

**Comment by jdearie** [comment]
I still need to grab the actual files that are located within the COD site vs linked to from comments.

Created a view to get this info - and just changed the slide field filter (null vs not null)
http://2014.capitalcampandgovdays.com/sessions/accepted/4archive

**Comment by timwood** [comment]
@jdearie The 2014 site is effectively down because decision not to renew domain. I'll create a final site/DB backup when I push up the new site.
