### ISSUE TITLE
google+ profile improvements

### ISSUE THREAD

**Issue by alisonjo315** [Drupal4Gov/Drupal-GovCon-2015#17]
- [x] set up url alias for G+ (and youtubte, etc.)
- [x] Change G+ image

**Comment by timwood** [comment]
Added better logo to G+ account.

**Comment by alisonjo315** [comment]
The way G+ (etc.) URL's work, you don't get much say in the matter, and the URL they're offering us is Drupal4Gov _plus additional characters_ (they say, "Many people have the same name. Add a few extra letters or numbers to this URL to get one that is unique for you.") -- but, no one is using this URL!

According to Google+ Help, your only recourse is to submit a feedback message and wait -- and keep checking back, sometimes the URL they offer you changes (but that might only be if you "ignore").

Source: Many posts on Google+ Help community, including: https://plus.google.com/108189659472078173316/posts/iEarVz5PaYi

**Comment by timwood** [comment]
Looks like this was resolved https://plus.google.com/u/0/+Drupal4Gov
