### ISSUE TITLE
Site-wide edit issues. Random nodes were not editable by even Admins

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2015#2]

**Comment by Nneka** [comment]
Roles are:
Administrator
Content Editor
Session Organizer
Sponsor Organizer
Attendee Manager
Administrator

Testing the roles listed above to see if I can recreate this problem in the new COD.

**Comment by timwood** [comment]
I think this may have been related to COD's complex permissions and specifically this issue: https://github.com/Drupal4Gov/Drupal-GovCon-2015/issues/1

@Nneka What did you find when testing  last month?
