### ISSUE TITLE
Theme landing page

### ISSUE THREAD

**Issue by Nneka** [Drupal4Gov/Drupal-GovCon-2015#21]

**Comment by jonraedeke** [comment]
Here's a start to the design of the home page. Some elements would change when the event is closer. For example, the navigation would have session schedule, sponsors, training, etc. Also, in place of the star for sponsors would probably be tickets or something.

![screen shot 2015-02-23 at 12 12 18 am](https://cloud.githubusercontent.com/assets/2054715/6323098/8e1ef912-baf1-11e4-81f9-bab58771dc61.png)

**Comment by jonraedeke** [comment]
Realized that pic of Dries is about 7 years old. I'll stick a new one in.

**Comment by timwood** [comment]
Looks great!

**Comment by timwood** [comment]
News header should probably be below sign up form. With it above sign up
form it implies, to me, that you are signing up for news. That's sort of
true, but I doubt we will email every news node to the participants email
list, right?

**Comment by jonraedeke** [comment]
good point

**Comment by jonraedeke** [comment]
Made some edits to the mockup:
- Add diamond sponsors at top
- Callout previous name of event
- Big ol' ticket button

![screen shot 2015-03-14 at 10 24 04 pm](https://cloud.githubusercontent.com/assets/2054715/6654415/23ad1a16-ca99-11e4-843e-1d4671fce0c4.png)

**Comment by timwood** [comment]
Looks great. Where will the session submission button go? Or should we fit
that in some other way?

**Comment by jonraedeke** [comment]
Let's replace "Program" with "Submit a Session" until the sessions are picked.

**Comment by timwood** [comment]
@jonraedeke Good idea, only problem is that node/add/session is not allowed by anonymous so it will not display for anon, meaning nor will the sub-items.

If we make it user/login?destination=node/add/session it doesn't show for logged in users!

If we make it user?destination=node/add/session it shows for both anon and authenticated but doesn't redirect to the right page for a logged in user. They get stuck on their user profile. :-(

**Comment by timwood** [comment]
We could have two menu items, one that works for anonymous and one for authenticated, but then we'll either have to repeat the menu sub-items under each or disable/move the sub-items.

**Comment by jonraedeke** [comment]
This is kind of dumb, but how about a basic page with instruction about logging in and submitting a session, what to expect etc.

Logged in users would have button on the page to "Submit your awesome session"
Anon users get "Log in to submit a session"

**Comment by timwood** [comment]
I'm going to add a page as you suggest.

**Comment by timwood** [comment]
Page created. Some base content added. @jonraedeke Please add image or whatever where I left you a place holder. https://capitalcampstg.prod.acquia-sites.com/drupal-govcon-2015/submit-session

**Comment by timwood** [comment]
LOOKING GOOD!!!

**Comment by jonraedeke** [comment]
This thread is a little scattered, so I'll open smaller tasks when new elements are added to the homepage, like twitter feed, session icons etc.
