### ISSUE TITLE
Build Landing Page

### ISSUE THREAD

**Issue by Nneka** [Drupal4Gov/Drupal-GovCon-2015#22]
Stuff for home page
- [x] Navigation (this probably could come later)
- [x] General event info (name, dates, location)
- [x] Featured keynote
- [ ] Subscribe for updates
- [x] News list (1-5 items long)
- [ ] Social media links/icons
- [x] Session tracks (pane there, waiting on icons)
- [x] Diamond sponsors in top (pane there, needs styling)
- [ ] Become a sponsor
- [X] Submit a session
- [X] Apply for scholarship

The old site home page was controlled/built using a mix of:
- Drupal theming (for the large banner with the name)
- Drupal's default blocks interface (to place the "nice" menu at the top, main page content and footer)
- and the system node page/panel for the bulk of the page contents with some basic visibility rules for certain panes (rendered node, news view block, tweets pane, sponsors view side-bar & sponsors view footer)

The node page panel was also used for all other nodes, except for session nodes, which had it's own variant in the panel.

So what do we want to do with the new site? What do we want on the new site? Lets think out the structure of the page, so we can decide how best to build it.

**Comment by timwood** [comment]
@jonraedeke @Nneka @alisonjo2786 
What do we think should go on the homepage to begin with? How's this list for starters?
- Navigation (this probably could come later)
- General event info (name, dates, location, featured keynote)
- Subscribe for updates
- News list (1-5 items long)
- Social media links/icons
- Become a sponsor
- Submit a session
- Apply for scholarship

**Comment by jonraedeke** [comment]
@timwood This looks like a good list. I can't think of anything else. I'm working on a home page mockup. Feel free to add raw info to the site in the mean time.

**Comment by timwood** [comment]
I'd like to have a discussion and perhaps consensus about how we should manage the home page (and others) in COD. Certain elements that are common for all pages (navigation/banner, footer, sponsors) should be in the theme, placed via context, the default block system or other site-wide mechanism/module. 

But we should also consider that we plan to use this COD install for future events as it supports doing that. Each event is an Organic Group (on steroids) so multiple events can exist in one Drupal install, either as archives of past events or even concurrent events. The home page can be one, active event or provide info about multiple. Looks like the Drupal Association has started doing this with DrupalCon LA https://events.drupal.org/losangeles2015 although the Barcelona 2015 event isn't on that site yet and only appears to be a static, one-pager, so maybe the plan is to put it on events.drupal.org after LA or sometime sooner than that.

I'm also thinking about how the development, staging and production workflow will work. Do we have time & effort to codify all changes, overrides or modifications to COD that we make?

**Comment by jonraedeke** [comment]
> multiple events can exist in one Drupal install

@timwood Can we make this event url be http://drupalgovcon.org/2015 and have http://drupalgovcon.org/ point there? That way users would logically type a different year to access previous or upcoming events. Maybe this is what you were already alluding to.

From a theming perspective, we'll probably want to change up the look and feel each year. But given the timing, we could address that after the event with the themekey module per path or per OG and just make sub-sub-themes each year to tweak the look but not start from scratch. I will try to separate styling that is very event specific so we can keep overall layout grid etc.

> codify all changes, overrides or modifications to COD that we make?

I think we should try to do really broad features to codify the site. It's really harsh when changes have to be made on production due to the fact that there will be many users and multiple events.

**Comment by timwood** [comment]
I've added the redirect module and configured one redirect for / to the 2015 event node.

**Comment by alisonjo315** [comment]
That sounds awesome.  I'd be happy to help start the hp if there's even
just a very rough mockup to start -- or are we wanting to discuss more
first?

**Comment by timwood** [comment]
I started working on this because I was also working on some stuff for the registration page, but got hung up when my features overrides started to make default COD features overridden. ugh!

**Comment by timwood** [comment]
Okay. Got it to work! The home page (and any other event added later) is now rendered by a panelizer panel. COD came with a default panelizer panel, even though it wasn't enabled, so I left that alone and allowed selection of panelizer panel for conference/event content type and added a new panelizer panel called DGC 2015. 

I disabled the output of the event description (body) and dates, but we can add them later. I just thought they didn't fit very well without some additional styling.

There is a place for Sponsors, News, the session tracks are output via a view (and need styling).

**Comment by alisonjo315** [comment]
Sounds fantastic!

**Comment by timwood** [comment]
@jonraedeke is going to add big buttons for tickets and sessions submissions to the home page panelizer via simple link and styling.

**Comment by jonraedeke** [comment]
@timwood I decided to style the Diamond sponsors in a big beveled box full width above the News on the homepage and show only the other sponsors at the bottom. I might still change my mind and put it up to the right of the date.

![screen shot 2015-04-01 at 11 15 35 pm](https://cloud.githubusercontent.com/assets/2054715/6957350/ba8262de-d8c7-11e4-97ba-92593181fbde.png)

**Comment by alisonjo315** [comment]
​Pretty!​

**Comment by jonraedeke** [comment]
I do think I will move it up to the right after we get more content on the homepage. This takes up a lot of real estate. Good enough for now.

**Comment by timwood** [comment]
Looks great, Jon. I like the logos centered too.

In addition to session tracks, we are still missing Featured keynote (Dries' photo) and subscribe for updates box. I think these would be the next two most important things, after the session tracks. Thanks for working on this last night!

**Comment by timwood** [comment]
@jonraedeke Can you also apply the same styling treatment to the sponsors page view?

**Comment by timwood** [comment]
I was able to add the bevel class to the sponsors page view to style it a little. Doesn't highlight diamond over others on the page in anyway. Couldn't figure out how to make the views grouping use an H2 tag for the grouped field output. Changing the style/field of the grouped field in the field list did not help.

**Comment by jonraedeke** [comment]
> I was able to add the bevel class to the sponsors page view to style it a little.

Cool, thx

> Doesn't highlight diamond over others on the page in anyway.

Would you like it to?

> Couldn't figure out how to make the views grouping use an H2 tag for the grouped field output.

@timwood No worries, I can just style the H3. That's what I did on the home page.

**Comment by timwood** [comment]
I guess it doesn't have to highlight Diamond any differently on the sponsors page.

**Comment by jonraedeke** [comment]
@timwood I committed styling for the sponsor level h3 headings.

**Comment by timwood** [comment]
@jonraedeke If you have time, bump for session tracks and Featured keynote (Dries' photo) on home page.

**Comment by timwood** [comment]
I tried dropping the session track attachment view onto the home page panel, which worked okay, but I didn't want to leave it w/out your input and plus the bottom sponsors box did weird things (overlaying on top of all other objects) when the session tracks view was right above it in the pane order.

![image](https://cloud.githubusercontent.com/assets/91050/7106671/8bdf1190-e117-11e4-9070-a1dd1bf6affc.png)

**Comment by jonraedeke** [comment]
Tim, that will be a perfect way to add the tracks. Just do it in dev and I will fix the style bugs and probably display side by side.

**Comment by timwood** [comment]
Side by side sounds good. Maybe just large icons with title shown on hover?

**Comment by timwood** [comment]
So I decided to try placing the Sessions attachment view in the "top right" panel region and moving the news list to the "left content" panel region. The result is pretty decent, except that the breakpoint which causes the sessions pane to jump above the news is too late. I looked at other panel layout options, including the Omega page and content options, but couldn't decide on one that would work. If we can shorten news (maybe only list two items) or get the featured keynote object in there, I think the session tracks object can stay there. The screenshot below is how it looks and this is currently in develop branch.

![screen shot 2015-04-12 at 8 48 35 pm](https://cloud.githubusercontent.com/assets/91050/7108497/10861a54-e156-11e4-8197-c75bbe92d543.png)

Whoops, meant to put the sessions pane into "bottom right". @jonraedeke Please change if you get to this.

**Comment by timwood** [comment]
Just wanted to add this screenshot from issue https://github.com/Drupal4Gov/Drupal-GovCon-2015/issues/21#issuecomment-80802180 for reference here:
![screen shot 2015-03-14 at 10 24 04 pm](https://cloud.githubusercontent.com/assets/2054715/6654415/23ad1a16-ca99-11e4-843e-1d4671fce0c4.png)

**Comment by timwood** [comment]
Shifting to next milestone.

**Comment by timwood** [comment]
@jonraedeke Do you know when you might have some time to work on the home page?

**Comment by jonraedeke** [comment]
@timwood I hope to get the dries image and some news theming done tonight.

**Comment by jonraedeke** [comment]
@timwood I pushed the news styling (to include the date) and the Dries callout. Homepage still needs twitter feed, subscribe and social media links possibly.
![screen shot 2015-05-08 at 1 22 24 am](https://cloud.githubusercontent.com/assets/2054715/7531017/140470c0-f521-11e4-8130-7120999f9083.png)

**Comment by timwood** [comment]
Looks awesome!

**Comment by jonraedeke** [comment]
Added Twitter feed to homepage.
![screen shot 2015-05-15 at 11 40 09 pm](https://cloud.githubusercontent.com/assets/2054715/7664565/d958c354-fb5b-11e4-8715-03321a5d7afc.png)

**Comment by timwood** [comment]
@jonraedeke Looks great. What did you use to accomplish the twitter feed? I haven't had a chance to look yet.

**Comment by jonraedeke** [comment]
I just put the Twitter embed code straight into a custom panel pane since the Twitter Block module didn't featurize.

**Comment by timwood** [comment]
Created separate tasks for:
[Social media links/icons](https://github.com/Drupal4Gov/Drupal-GovCon-2015/issues/129)
[Subscribe for Updates](https://github.com/Drupal4Gov/Drupal-GovCon-2015/issues/130)

"Become a sponsor" item ended up as a main menu item.

Calling this issue done!
