### ISSUE TITLE
Drupal GovCon look and feel notes

### ISSUE THREAD

**Issue by jonraedeke** [Drupal4Gov/Drupal-GovCon-2015#23]
The group voted and chose the following look and feel for Drupal GovCon. I'm using this task to keep track of comment or notes about this styling.

![screen shot 2015-02-20 at 7 51 10 am](https://cloud.githubusercontent.com/assets/2054715/6286436/58284728-b8d5-11e4-9c3a-521bbfc6fdc9.png)

**Comment by jonraedeke** [comment]
Changed script font to "Courgette". Much more legible for h2.

**Comment by jdearie** [comment]
in support of the github cleanup, let's create a new issue for future requirements.
