### ISSUE TITLE
Add prospectus link (GDrive linked PDF) to splash page

### ISSUE THREAD

**Issue by timwood** [Drupal4Gov/Drupal-GovCon-2015#24]

**Comment by timwood** [comment]
Kirsten says it will be ready for posting early next week.

**Comment by bendygirl** [comment]
http://bit.ly/1GOlWoD is a shortened link to the prospectus

**Comment by jonraedeke** [comment]
How's this?

![sponsors](https://cloud.githubusercontent.com/assets/2054715/6652624/a26b9b14-ca4b-11e4-9900-df8163a93afc.png)

**Comment by timwood** [comment]
Looks great, Jon!

**Comment by bendygirl** [comment]
nice. There aren't many spots left for sponsoring, so doesn't need to be
above the fold.

On Sat, Mar 14, 2015 at 1:11 PM, Jon Raedeke notifications@github.com
wrote:

> How's this?
> 
> [image: sponsors]
> https://cloud.githubusercontent.com/assets/2054715/6652624/a26b9b14-ca4b-11e4-9900-df8163a93afc.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Drupal4Gov/Drupal-GovCon-2015/issues/24#issuecomment-80598088
> .

## 

Kirsten
http://uniongal.blogspot.com
Join Uniongal on Reddit http://www.reddit.com/r/Uniongal/

**Comment by timwood** [comment]
Done now!
