### ISSUE TITLE
Research and implement improved registration/login module

### ISSUE THREAD

**Issue by timwood** [Drupal4Gov/Drupal-GovCon-2015#27]
Username's are so 2000's, why not use email address instead? What about external authentication options like G+, FB, Twitter, etc?

Options:
- https://www.drupal.org/project/logintoboggan
- https://www.drupal.org/project/email_registration
- https://www.drupal.org/project/super_login
- https://www.drupal.org/project/hybridauth
- https://www.drupal.org/project/friendly_register ?

Good post about logintobaggan and email_registration differences: http://www.grasmash.com/article/using-your-email-address-your-drupal-username

**Comment by timwood** [comment]
@jdearie @Nneka @alisonjo2786 @jonraedeke Do we care about the privacy of our users (and our own) email addresses? On the 2014 site we didn't expose user email addresses to anonymous or registered user. We had a simple profile page with contact form (which is optional in COD).

**Comment by Nneka** [comment]
I think we should do the same this year.  Unless you provide a checkbox
that allows users to tell you whether they want their e-mail addresses
shared.  I know I care about my privacy of my e-mail address.

**Comment by alisonjo315** [comment]
I agree with Nneka.

Alison Jo McCauley
alisonjo2786@gmail.com
facebook https://www.facebook.com/alison.jo.mccauley | twitter
https://twitter.com/alisonjo2786 | linkedin
http://www.linkedin.com/in/ajmccauley

**Comment by timwood** [comment]
Okay. So we won't do what the article I linked to did by making the username the registrants email address. Thanks for the input.

**Comment by timwood** [comment]
Logintoboggan and Super Login modules added and automatically enabled via dgc_deploy feature. Super log in module makes login form look like this:
![screen shot 2015-03-09 at 12 32 40 am](https://cloud.githubusercontent.com/assets/91050/6549994/15f94bdc-c5f4-11e4-9483-938208c7c9fa.png)

Logintoboggan provides some nice messaging upon login and when attempting to access a protected resource, when not logged in. Plus it adds a confirm email address on account registration form.
![screen shot 2015-03-09 at 12 36 31 am](https://cloud.githubusercontent.com/assets/91050/6550017/81342ed0-c5f4-11e4-9685-d70caa68f986.png)

![screen shot 2015-03-09 at 12 33 12 am](https://cloud.githubusercontent.com/assets/91050/6550019/876060b2-c5f4-11e4-8c5d-7f77c1e209bc.png)

**Comment by timwood** [comment]
Hybridauth is quite a lot more involved than I realized. You need to apply as an application for each provider to get an API key/secret. Decide against it for now.

**Comment by timwood** [comment]
Going to close this and worry about registering via FB, Twitter, Google, etc. next year.
