### ISSUE TITLE
Configure 2015 event in staging site

### ISSUE THREAD

**Issue by timwood** [Drupal4Gov/Drupal-GovCon-2015#29]
Need:
- [x] Exact event times (8:00am - 4:00pm 7/22 - 7/24)
- [x] FREE Ticket
  - Tickets to the event are free, but Required. Please register to reserve your ticket.
  - 3/17 start date?
  - Total quantity: 1100
  - Min: 1
  - Max: 10
  - Default state: Completed
- [x] Session Tracks (decided at 2/12 meeting)
  - PHP, Javascript, and DevOps
  - Business Intelligence, Case Studies, Non-Profit, and Government
  - Configuration, Testing, and Site Building
  - User Experience and Design
  - Training
  - Keynote (COD scheduling thing)
- [ ] ~~Rooms/location ([See spreadsheet](https://docs.google.com/a/buchbinder.org/spreadsheets/d/17bBGonGb0M9AEx3MAaLdn-GfzRfFfUUWqZB71rnwtJI/edit#gid=18))~~
- [ ] ~~Timeslots ([See spreadsheet](https://docs.google.com/a/buchbinder.org/spreadsheets/d/17bBGonGb0M9AEx3MAaLdn-GfzRfFfUUWqZB71rnwtJI/edit#gid=18))~~

**Comment by bendygirl** [comment]
Times, dates, rooms are here for sessions https://docs.google.com/a/buchbinder.org/spreadsheets/d/17bBGonGb0M9AEx3MAaLdn-GfzRfFfUUWqZB71rnwtJI/edit#gid=18

**Comment by timwood** [comment]
Great, thanks for that!

Should we use last year's session tracks? http://2014.capitalcampandgovdays.com/admin/structure/taxonomy/session_tracks_1
- Code and DevOps
- Drupal Business, Case Studies, Non-Profit and Government
- Configuration, Testing and Site Building
- Design / User Experience
- Security
- Training
- Keynote

**Comment by bendygirl** [comment]
For ticket types, we can do Gov and non Gov, but I'd rather just do a check box and one ticket type since this is really not necessary since we don't do multiple types 

https://docs.google.com/spreadsheets/d/17bBGonGb0M9AEx3MAaLdn-GfzRfFfUUWqZB71rnwtJI/edit#gid=18

ignore the first link use this one.

**Comment by timwood** [comment]
First link replaced with correct one.

**Comment by bendygirl** [comment]
For tracks, we mimicked Drupalcon.  https://events.drupal.org/losangeles2015/sessions/proposed But there are a lot more this year.

**Comment by timwood** [comment]
@bendygirl Do you think there's any reason to do different ticket types? Do we need to keep sponsor tickets to a certain number?

**Comment by bendygirl** [comment]
Code and DevOps
Drupal Business, Case Studies, Non-Profit and Government (we don't really need this)
Project/Product Management (add this one in)
Configuration and Site Building
Design / User Experience
Testing and Security 
Training
Keynote

**Comment by bendygirl** [comment]
@timwood no, I don't think we actually need different ticket types. Sponsors are only limited in that they need to register everyone. It's the only way we can gage how many lunches to buy or T-shirts to order.

**Comment by bendygirl** [comment]
Total quantity 1100 total quantity at this time. We expect 800, so that will allow us to have the traditional drop off amount
Min per order - at least 1.
Max per order, no more than 10, that seems reasonable.

**Comment by bendygirl** [comment]
I wasn't able to do this last year, but a ticket does not have to be related to an individual user. This didn't work well on last year's site. So, when a scheduler or a assistant goes in and needs to book two tickets (or I need to do it for a keynote), the ticket should be sortable by the ticketed attendee not the ticket requester.

**Comment by timwood** [comment]
Most rooms added, but the whole scheduling process is insanely long! Here's a short video about how to do it. https://www.youtube.com/watch?v=1S7SjMMXOx4

**Comment by bendygirl** [comment]
@timwood the scheduling is long, but the session selection team should be able to handle this fairly easily as long as we know which rooms and times need to be filled with tracks.

**Comment by timwood** [comment]
Let's move the last two checkboxes to separate tasks since they are much more involved and come much later, which I didn't understand when I created the list.
