### ISSUE TITLE
Tweak tickets registration view to show attendee info instead of or in addition to registrant info

### ISSUE THREAD

**Issue by timwood** [Drupal4Gov/Drupal-GovCon-2015#31]
The default COD list of ticket registrations at /admin/structure/views/view/ticket_registration/edit/default has columns for "Name" and "E-mail" but they are the registrant's info instead of the attendee. This should list attendee info and add a field for the registrant info. If needed, model it off of community view /admin/structure/views/view/cod_community_attendees/edit ?
- [x] Preface "Name" and "E-mail" fields labels with "Attendee"
- [x] Add field for registrant: name with E-mail in parens or something
- [x] Make view in to a VBO?
- [x] Do all this properly by exporting an overridden view via Features Overrides or something like that

**Comment by Nneka** [comment]
Fixed this.  Waiting for Tim to view and feature it.

**Comment by timwood** [comment]
Can you make attendee column link to the user entity like the view used to?

**Comment by timwood** [comment]
Also, the email column is still the registrant's email, not the attendee.

**Comment by Nneka** [comment]
Attendee column is linking to the user entity  

Fixing the registrants e-mail.  The registrants email isn't saved when entering in a ticket registration.  It seems to be saved as the user name for that registrant.  Still looking...
http://capitalcampdev.prod.acquia-sites.com/ticket_registration/81/edit

**Comment by timwood** [comment]
Yeah, it's a stub of a user account that is created I believe. Only the email is included, but as the username. You could just show the username?

**Comment by timwood** [comment]
@Nneka The view needed another relationship to get at the attendee fields.
