### ISSUE TITLE
Registration improvements

### ISSUE THREAD

**Issue by timwood** [Drupal4Gov/Drupal-GovCon-2015#33]
- [x] Add message on registration page letting the user know whether they've already registered for tickets.
  - [x] Only show for non-anonymous user.
- [ ] Limit tickets per X period?
- [x] Copy user fields to ticket registration
  - [x] Dietary needs (required)
    - [x] Add "no" option
  - [x] T-Shirt size (required)
    - [x] Small, Large, 2XL
  - [x] First Name
  - [x] Last Name
  - [x] Government Employee (checkbox)
- [x] Add email confirmation -- "Here are your tickets"

**Comment by timwood** [comment]
I added two view content panes to the registration page and home page (both places where the initial tickets form appears). One lists the current, logged in users ticket(s) registered by them and the other lists tickets they've registered with view, edit and cancel links. I think this still needs tweaking.

![image](https://cloud.githubusercontent.com/assets/91050/6650611/5a5de5c8-c9f3-11e4-8992-36e557f4c201.png)

**Comment by bendygirl** [comment]
This is a great idea for the folks who have to register more than themselves.

**Comment by timwood** [comment]
At /ticket_registration/manage/1/fields we can copy user fields to be used on the ticket form. The values entered then get transferred to the user object when the account registration is complete.

Fields listed in the task description copied!

**Comment by timwood** [comment]
> Add email confirmation -- "Here are your tickets"

I attempted to add a rule to react to ticket creation and send separate email, but was unable to successfully create the rule. Then I realized we already have an email going out to registrants, which was more focused on account creation. So I modified the email for account and ticket.

**Comment by timwood** [comment]
Email language is the following:

Subject:
Your new account at [site:name] and tickets!

Body:
Hi [user:name]. Welcome to [site:name]!

You've been registered for [site:name] and have secured a ticket to the event. You may now log in by clicking this link or copying and pasting it to your browser:
[user:one-time-login-url]

This link can only be used once to log in and will lead you to a page where you can set your password, change your username if you choose, and fill out your profile.

After setting your password, you will be able to log in at [site:login-url] in the future. Make sure to visit the website for updates leading up to the event.
email or username: [user:name]
password: Your password (that you set)

Subscribe to our newsletter:
http://eepurl.com/bbJASn

Follow us on social media:
https://twitter.com/drupalgovcon
https://plus.google.com/+Drupal4Gov
https://www.facebook.com/DrupalGovCon

--  [site:name] team

**Comment by alisonjo315** [comment]
"Dietary needs (required) >> Add "no" option" -- I think "None" should be selected by default.  Thoughts?

**Comment by bendygirl** [comment]
The problem last year were the folks who cried FOUL because there was no
gluten free or halal or kosher, etc.. for them because even though the item
was there and we asked, they didn't complete it. So wherever will work that
makes them do something (select an option), I'm good with anything as
default, as long as they select something including None.

On Mon, Mar 16, 2015 at 2:32 PM, alisonjo2786 notifications@github.com
wrote:

> "Dietary needs (required) >> Add "no" option" -- I think "None" should be
> selected by default. Thoughts?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Drupal4Gov/Drupal-GovCon-2015/issues/33#issuecomment-81856999
> .

## 

Kirsten
http://uniongal.blogspot.com
Join Uniongal on Reddit http://www.reddit.com/r/Uniongal/

**Comment by alisonjo315** [comment]
Ok no, that makes sense -- leave it as-is :)
