### ISSUE TITLE
Sponsor page tweak

### ISSUE THREAD

**Issue by bendygirl** [Drupal4Gov/Drupal-GovCon-2015#35]
Tweak the sponsors view to output only logo  that links to sponsor's website/page, grouped by level. Similar to drupalconLA https://events.drupal.org/losangeles2015/sponsors

**Comment by timwood** [comment]
This is now done. @jonraedeke FYI. The sponsors can now be styled.

**Comment by timwood** [comment]
Links to sponsors home page doesn't seem to work.

**Comment by timwood** [comment]
When using features overrides on a view it doesn't seem to record the field order, which is why this was broken. To fix, save proper order on live site manually. It will not override the feature!
