### ISSUE TITLE
Create Thank you what's next page

### ISSUE THREAD

**Issue by timwood** [Drupal4Gov/Drupal-GovCon-2015#36]
- [x] Set path alias to thankyou
  Add page of content with thank you for getting tickets message and perhaps "what's next" info.
- [x] Thank you for registering for tickets
- [x] Link to page with directions to NIH
- [x] Link to page with hotel info to the local stays
- [x] next steps
- [x] deadlines (updated info as deadlines pass for scholarships, sessions, etc)
- [x] Link to submit session

**Comment by timwood** [comment]
@jdearie @alisonjo2786 @Nneka @bendygirl can one of you let me know whether this content was already created?

**Comment by timwood** [comment]
Initial page created: https://capitalcampstg.prod.acquia-sites.com/thankyou

**Comment by bendygirl** [comment]
Okay, so add:
- Thank you for registering for tickets
- directions to NIH
- hotel info to the local stays
- next steps
- deadlines (updated info as deadlines pass for scholarships, sessions, etc)

**Comment by timwood** [comment]
Anything that is already another page, should be a link, of course.

**Comment by timwood** [comment]
I added your items and one more to the task at the top. Let me know whether you can see the checkboxes.

**Comment by ninaogor** [comment]
Got it! Let you know in a second!

On Sun, Mar 15, 2015 at 12:43 PM, Tim Wood notifications@github.com wrote:

> I added your items and one more to the task at the top. Let me know
> whether you can see the checkboxes.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Drupal4Gov/Drupal-GovCon-2015/issues/36#issuecomment-81148880
> .

## 

Nina Ogor
College of Arts and Humanities
University of Maryland-College Park
Senior, Persian Studies and Women's Studies Double Major
puffg9@gmail.com
202-341-1737

**Comment by ninaogor** [comment]
I've linked everything. Here are the links I'm using. I'm going to add something on Github for the FAQs page. 

http://drupalgovcon.org/faqs (for session)
http://drupalgovcon.org/scholarships (for scholarships)
http://drupalgovcon.org/travel-and-directions (event location)
http://drupalgovcon.org/where-stay (hotels)

**Comment by timwood** [comment]
Why does the sessions link go to faq? Shouldn't it go to node/add/session ?

Also, I recommend changing the link text to use the whole second sentence "Click here and submit your idea". So the whole sentence should be the link.

By relative links I meant they should start with no http: so the href would be /drupal-govcon-2015/scholarships Same with the others.

**Comment by ninaogor** [comment]
Yup, it should. That's my fault. Understood my mom wrong. 

got it. I'll change the language and make the whole sentence the link

oh! I see. okay. I'll change the links. 

Thanks Tim!

**Comment by timwood** [comment]
I've updated the thank you page with the changes discussed.
