### ISSUE TITLE
Style comments

### ISSUE THREAD

**Issue by timwood** [Drupal4Gov/Drupal-GovCon-2015#39]
Comments need a little love.

![image](https://cloud.githubusercontent.com/assets/91050/6656308/e754cc36-cafb-11e4-9a67-902fd6da5243.png)

**Comment by jonraedeke** [comment]
Are we accepting comments anywhere currently or only after sessions are approved?
Just gauging priority.

**Comment by timwood** [comment]
News has open comments and I think it should stay that way. It's open for authenticated users only, not anon.

**Comment by timwood** [comment]
Also will be open for sessions and bof-sessions.

**Comment by jonraedeke** [comment]
Committed to develop branch.

![comment_style](https://cloud.githubusercontent.com/assets/2054715/6689788/d0202324-cc92-11e4-8b95-beca044930db.png)
