### ISSUE TITLE
Ordering of rooms or sessions was by date added.

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2015#4]

**Comment by Nneka** [comment]
The page causing issues:  http://2014.capitalcampandgovdays.com/team-session-review?sort_by=field_session_timeslot_target_id&sort_order=ASC

Sessions are not fully being sorted by date.

Will build out sessions in the updated COD distro to see if I can recreate the problem.  Will first enter in about 10 to 20.  I will then go back and update a session to see if it continues to sort as it should.

**Comment by Nneka** [comment]
A new cod distro was released January 7, 2015.

**Comment by Nneka** [comment]
This view no longer exists and is probably been replaced by another view.    There's a new view (admin/conference/1/schedule) that uses tab for each date.  Sessions seem to be sorting correctly.  

Tested this only local computer.  Don't see the problem occurring.

http://localhost:30080/admin/conference/1/schedule

**Comment by timwood** [comment]
Based on @Nneka's findings I'm closing this issue. Thanks!
