### ISSUE TITLE
Add content to FAQ page

### ISSUE THREAD

**Issue by ninaogor** [Drupal4Gov/Drupal-GovCon-2015#40]

**Comment by bendygirl** [comment]
From old site:

FAQs

Q: What is Drupal?

Drupal is an open source content management system software.  Learn more about Drupal on Drupal.org

Q: Who attends CapitalCamp and Gov Days?

This 3 day Drupal camp is for anyone interested in learning Drupal and connecting with the Drupal community.  There will also be specific content targeted to Drupal for government web solutions.

Q: Do I need to be proficient in Drupal to participate in the camp?

The session schedule will provide learning opportunities for every level of Drupaler, whether you are just starting to learn Drupal or if you are an advanced Drupal developer.  If you are a beginner, we suggest you register for one of the trainings offered during the camp to get you ready to learn!

Q: What are the session track topics?

The session tracks include:

Development/Coding
Theming/UX
Design
Business Strategy
Q: Who can submit a session?

Anyone can submit a session and we encourage you to do so! A committee of volunteers will vote on what sessions get accepted and will build the session schedule.

Q: What is the session deadline?

The session deadline is June 30th! Submit today!

Q: What do I need to bring to the camp?

We suggest a computer/tablet if you want to take notes during the sessions.  Remember to bring a charger!

Q: How can I stay up-to-date on all camp news and announcements?

Be sure to follow us on @CapitalCampDC, the DC Drupal group, and the news section of our website!

**Comment by jdearie** [comment]
Current content says "DON'T TOUCH" at the top of the page. Becca had updated/drafted FAQs, can i update the page with her content or are we leaving the FAQ page alone for now?

**Comment by timwood** [comment]
@bendygirl @ninaogor Should know more about why it says don't touch.

**Comment by bendygirl** [comment]
yes, update. Nina was scoping it out, but feel free to edit.

K

On Mon, Mar 16, 2015 at 11:20 AM, Jessica Dearie notifications@github.com
wrote:

> Current content says "DON'T TOUCH" at the top of the page. Becca had
> updated/drafted FAQs, can i update the page with her content or are we
> leaving the FAQ page alone for now?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Drupal4Gov/Drupal-GovCon-2015/issues/40#issuecomment-81731095
> .

## 

Kirsten
http://uniongal.blogspot.com
Join Uniongal on Reddit http://www.reddit.com/r/Uniongal/

**Comment by dsheffler** [comment]
Jess, if you add it in, I'm going to work on editing content later this
afternoon so I can make the updates.

**Comment by jdearie** [comment]
@bendygirl - the content that Nina has does not match what Becca did.  I've posted Becca's content on google drive in a folder called content drafts. Which one do we want to use?

The FAQs on the site seem to have more content, but the registration instructions need updating.

**Comment by jdearie** [comment]
ok - i copied what was on the site and created a google doc labeled Nina FAQs. That way we grab any of what she started if we need to.

I updated the page with the FAQs that Becca drafted - but we'll still need to ensure the session tracks are correct and that we have the correct session submission deadline.

@dsheffler is going to review and make edits this afternoon. I'll assume she'll close this issue when she's done. Thx @dsheffler !

**Comment by bendygirl** [comment]
perhaps we should include a link to the DrupalCon convince your boss page? https://events.drupal.org/losangeles2015/convince-your-boss

**Comment by dsheffler** [comment]
It's already there in the sitemap :)

**Comment by bendygirl** [comment]
duh, it totally is!

**Comment by dsheffler** [comment]
This content has been added and reviewed. Closing.
