### ISSUE TITLE
Add first news article so it's not blank

### ISSUE THREAD

**Issue by timwood** [Drupal4Gov/Drupal-GovCon-2015#43]
We need a new item. Welcome news item. Registration open. Something.

**Comment by timwood** [comment]
@bendygirl @ninaogor @alisonjo2786 @jdearie @dsheffler Do we have something for this already?

**Comment by alisonjo315** [comment]
We could post what we put on GDO about the prospectus and sponsorship
opportunities?

**Comment by timwood** [comment]
@jdearie Started a page here: https://capitalcampstg.prod.acquia-sites.com/drupal-govcon-2015/news/welcome

Feel free to add to it anyone.

**Comment by dsheffler** [comment]
This has been created on the live site.
