### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by jonraedeke** [Drupal4Gov/Drupal-GovCon-2015#44]
What needs to be in the footer?
- Brought to you by Drupal4Gov
- Site map?

Here's the one from Drupalcon LA

![screen shot 2015-03-15 at 11 24 34 pm](https://cloud.githubusercontent.com/assets/2054715/6660171/8ae17e1c-cb6a-11e4-88b3-873b0ee30799.png)

**Comment by timwood** [comment]
No idea. On the old site we just had the COD credit. Maybe for now we don't need anything else?
![image](https://cloud.githubusercontent.com/assets/91050/6660283/5f1830f8-cb6c-11e4-88ca-ed319a7365bf.png)

In case you want to look at the old site here is google cache: http://webcache.googleusercontent.com/search?q=cache:ScsGAzQp4KcJ:2014.capitalcampandgovdays.com/+&cd=1&hl=en&ct=clnk&gl=us

**Comment by alisonjo315** [comment]
I think minimal is good.  Maybe like... a link to D.O and maybe to
Twitter/G+/GDO...?

**Comment by jdearie** [comment]
I have a super basic page up at drupal4gov.us  

Think we can link to that, or would you prefer it look nicer before we do?

**Comment by timwood** [comment]
Oh, cool. Didn't know anyone was working on that. I mean, I vaguely remember you mentioning it Jess. By the way, did you know the domain www.drupalforgov.org is owned by someone and DNS is pointing to and Acquia is configured for in the CapCamp acquia site?

**Comment by timwood** [comment]
James King also suggested repeating the main menu in the footer, which isn't such a bad idea.

**Comment by dsheffler** [comment]
From a UX/IA perspective, having the main menu in the footer gives the user more options for navigation, which is never a bad thing.

**Comment by timwood** [comment]
I've added the default main menu block to the footer and set all the top level menu items with sub-items to show expanded. It ends up looking like the screenshot below (desktop and then mobie). If everyone is okay with it, I'll commit an update hook to enable this block on the live site.

![screen shot 2015-03-29 at 2 42 06 pm](https://cloud.githubusercontent.com/assets/91050/6887106/9af6d398-d622-11e4-8777-2f7fb4ba88a2.png)

![screen shot 2015-03-29 at 2 44 08 pm](https://cloud.githubusercontent.com/assets/91050/6887105/9aec7b78-d622-11e4-9f6c-1294c50a3a18.png)

**Comment by dsheffler** [comment]
Could we update the styling so it looks like the Drupalcon LA site? It's just cleaner and easier to read.

**Comment by timwood** [comment]
Will leave that up to @jonraedeke

**Comment by jonraedeke** [comment]
Committed some basic styling.

![footer_menu](https://cloud.githubusercontent.com/assets/2054715/7311447/80f9d822-ea0a-11e4-8d88-54b5fd0a7bf3.png)

**Comment by timwood** [comment]
Much better!
