### ISSUE TITLE
Move sponsors to block via mini-panel or something

### ISSUE THREAD

**Issue by timwood** [Drupal4Gov/Drupal-GovCon-2015#47]
So we can have the lower sponsors block on every page instead of just the home page.

**Comment by timwood** [comment]
@bendygirl @jdearie How important do you feel it is to have sponsors listed/presented on every page of the site? DrupalConLA has their two Diamond sponsors at top of every page and only platinum sponsors at the bottom of every page. All other levels only appear on the dedicated Sponsors page. We have less sponsors and less levels.

We plan on moving the Diamonds sponsors to a dedicated part at the top of the homepage. I think what we have at the bottom of the homepage right now is too long to go on every page on the site. Can we just stick with sponsors on the homepage and dedicates Sponsors page?

**Comment by bendygirl** [comment]
Diamond and platinum should have awesome placement. Gold and silver should be on a sponsor page.

**Comment by timwood** [comment]
I think we've decided we don't need sponsors on every page.
