### ISSUE TITLE
Add content and form to Scholarships page

### ISSUE THREAD

**Issue by timwood** [Drupal4Gov/Drupal-GovCon-2015#48]
Info and dates?
https://capitalcampstg.prod.acquia-sites.com/drupal-govcon-2015/scholarships

**Comment by bendygirl** [comment]
added content. Dates dependent on Sessions as we need to close this after session selection.

The Drupal GovCon Scholarship Program will provide travel funds for this year's Drupal GovCon event (formerly known as Drupal Government Days and Capital Camp).

Attendance at Drupal GovCon will benefit the scholarship recipient with a Drupal GovCon experience and many of the benefits of the larger Drupal Community from networking to learning how to hold local events, sprints or to simply learn more about the Drupal project. 

Recipients will be selected based on their financial need, active contributions and dedication to growing Drupal through code, community leadership, and  mentoring. Additionally, recipients will be expected to volunteer for the equivalent of one half day during the event.

The Scholarship application will be available soon.

**Comment by dsheffler** [comment]
I added the content, but we should keep this open since we will want to include the webform on this page.

**Comment by bendygirl** [comment]
agreed, this should stay open until scholarships go live.

**Comment by timwood** [comment]
Webform on the page will require that we enable webform for the Page content type. Should be a minor development task/COD override.

**Comment by dsheffler** [comment]
Please see the form here: https://docs.google.com/forms/d/1XssEnWeP2ZlEPK-vSW-OvES5a8RAAD20KJwNktbQa7U/viewform

**Comment by timwood** [comment]
Thanks for the scholarship Gdocs form link. Looks like this was built for the 2015 event, but we still want to move it to the website? I know you've said this before Danielle, just confused by 2015 info in the form.

**Comment by dsheffler** [comment]
This GDoc was created since we didn't know when scholarships would be going
out. So no worries on the confusion but yes, please create this form in the
website. :)

**Comment by Nneka** [comment]
Will have this form created by tomorrow.  
Attaching the form to this page -->  https://www.drupalgovcon.org/drupal-govcon-2015/scholarships

**Comment by bendygirl** [comment]
We finalized the lines of the scholarship form last week. The personal statement should be no longer than 2000 characters (hopefully no more than 500 words).

**Comment by bendygirl** [comment]
@Nneka and for these questions:  

My employer is not paying for any expenses related to DrupalGovCon *

I am not a member of the DrupalGovCon planning committee. *

We don't need "True or False" answers, we just need to know they aren't part of the committee and if they're full self funded or not.

**Comment by Nneka** [comment]
Form has been created.

@bendygirl Unable to limit the amount of characters that users can enter in the personal statement text area.  Didn't find an option to allow me to limit the text.  Only occurs on the textfield control.  I did add text saying limit responses to 500 words or less.

Added one radio button for the not a member of the Drupalgovcon and expense questions..

Question.. Once the form is submitted, what will be the confirmation text?

**Comment by Nneka** [comment]
https://www.drupalgovcon.org/drupal-govcon-2015/scholarships

**Comment by dsheffler** [comment]
@Nneka, this looks great! It looks like my text about the scholarship form being available at the end of April is still on there. Are you ok with me going in to edit the page or would you rather take care of it?

Also, could we make the radio buttons checkboxes? I thought it was an either/or when I took a look.

**Comment by bendygirl** [comment]
@Nneka Thanks Nneka!! Looks great.

 My employer is not paying for any expenses related to DrupalGovCon

That question above, I think that it is not necessarily helpful. I think when we decided it, we were looking to just find out if the person planning to come is getting any funds from their employer. I feel like maybe it will discourage people from applying if the employer is funding some of it but not all.

Maybe we could re-write it.

**Comment by Nneka** [comment]
@dsheffler  Feel free to edit.  You'd do a better job than I.  Changed the radio buttons to checkboxes.

@bendygirl Hhmm...  The purpose of this question is to weed out potential attendees who have most of their conference costs paid?

Employer has contributed to DrupalGovCon expenses
Employer has paid 50% of DrupalGovCon expenses..
All expenses to attend DrupalGovCon have been paid by me

_shrug_

**Comment by bendygirl** [comment]
Yeah, I recall talking about wanting to know if they were getting anything. But now I'm not sure it's necessary.

**Comment by cmndr-king** [comment]
Sorry for the delay.  My goal with this question is to prevent double-dipping.  I don’t want someone to apply who is being fully funded by their employer and trying to get funds from us to simply pocket.  The goal is to ensure that we filter out those who are not in need.  It doesn’t have to be complex and can be covered in the narrative.

What if we simply eliminate this check box and change the text under the narrative to say "Why should you be awarded the DrupalGovCon Travel Award? Please address financial need, employer travel contribution, past contribution to Drupal, professional goals, and past attendance at Drupal conferences. Limit personal statement to 500 words or less."

We can eliminate the other check box by changing the opening text to say "This scholarship not available to any member of the Drupal GovCon planning committee."

**Comment by cmndr-king** [comment]
Hope you don't mind but I took a crack at editing the opening text.  I added in my suggestion and also cleaned up the flow of the text.  Feel free to change if you don't like it.

**Comment by dsheffler** [comment]
@cmndr-king, the text looks great!

@Nneka, the instructional text underneath some of the fields on the webform has DrupalGovCon has one word when it should be Drupal GovCon. I didn't want to change anything in case it was part of a feature.

**Comment by timwood** [comment]
@dsheffler Forms are not featurized. I've made the corrections.

**Comment by timwood** [comment]
Looks like this is done. Closing.
