### ISSUE TITLE
Random registration errors. Test Email Confirmation (SMTP)

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2015#5]
Email confirmation messages didn’t go out. Maybe look into using Mailchimp integration for sending emails.

**Comment by Nneka** [comment]
Server level issue.  Wonder if the server was set up for SMTP.  This is a server issue that can be resolved with troubleshooting.  

The only real way to test this now would be to test on the server that will house the DrupalGovCon website.  

As soon as the site website is setup on the server, this should be one of the first things that should be tested.

Ticket should remain open and addressed during website setup.

**Comment by timwood** [comment]
I've been doing various testing of registration in dev and test and I've received every email without problem.
