### ISSUE TITLE
Add content to "Code of conduct" page or unpublish & disable menu item

### ISSUE THREAD

**Issue by timwood** [Drupal4Gov/Drupal-GovCon-2015#50]
https://capitalcampstg.prod.acquia-sites.com/drupal-govcon-2015/code-conduct

**Comment by jdearie** [comment]
Content posted. Becca and I discussed it and felt that we could just grab from drupalcon, make a few small edits, and post as is.  If anyone has comments or suggestions on modifications, just let us know.

**Comment by timwood** [comment]
YOU ROCK!
