### ISSUE TITLE
Add content to "Social events" page or disable menu & unpublish

### ISSUE THREAD

**Issue by timwood** [Drupal4Gov/Drupal-GovCon-2015#52]
https://capitalcampstg.prod.acquia-sites.com/drupal-govcon-2015/social-events

**Comment by bendygirl** [comment]
Disable menu for now as this will be announced in the future, once contracts have been signed. Should be early May. Keep the issue open for when this will come up, but May 1st as earliest time frame for announcement.

**Comment by timwood** [comment]
@bendygirl We missed the April 30 milestone which I included this in. Should I move it to another milestone, disassociate with any milestone or other suggestion?

**Comment by bendygirl** [comment]
I would prefer that we move it to the next milestone, assuming we don't have too much more slippage from the schedule. But sessions haven't been finalized yet. We should start plotting this week while at Drupalcon.

**Comment by timwood** [comment]
If you don't have time and want to assign to someone else, feel free to do that here or via email. I'd think most of the social events are already scheduled and independent of the daily event schedule, right?

**Comment by bendygirl** [comment]
yes. Nina has been working to finalize the happy hour. Since we don't yet have a sponsor for trivia, we might not be doing that, but we will see.

**Comment by timwood** [comment]
Moving to "print date" milestone. Can we get this up soon?

**Comment by bendygirl** [comment]
soon, but not ready for this yet.

**Comment by timwood** [comment]
Looks like this is done.
