### ISSUE TITLE
Standardize Drupal GovCon References

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2015#53]
I've noticed that we are using a variety of different ways of spelling/stating the conference name.
Places to fix:
- [ ] Facebook name

I thought we were Drupal GovCon, but I'm seeing:

Drupal Gov Con
DrupalGovCon
... and misc other spellings.

The footer is using Drupal GovCon, which is my personal preference.

I'll scan all the online text and make the modifications, but for anyone adding content, please standardize on Drupal GovCon when spelling out the conference name.

**Comment by timwood** [comment]
I agree. I thought we decided on Drupal GovCon. I've noticed others use some of the various of the other spellings too. https://www.facebook.com/DrupalGovCon for example, although I'm not sure whether you can make your name have a space where displayed. Let's use this task to make a list of places we notice it wrong.

**Comment by jdearie** [comment]
Pretty sure I got all of them.

**Comment by timwood** [comment]
I see some in the Gdocs scholarship form, which I'm converting into a webform on the website, so I'll fix those when I convert.
