### ISSUE TITLE
Registration Feedback

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2015#54]
I registered for an account this morning... 
- [x] we may want to add some text stating that a new account is required even if you've attended previous capitalcamp/gov days before.
- [x] the confirmation email came from tim@buchbinder.org - we should probably change that ;)  

~~3 - the confirmation email told me login was the email address i used and the password i set up. however - when i registered, there was no opportunity to create a password.~~
- [x] In the registration email template replace the (that you set) with (that you will set after clicking on the link above).

**Comment by jdearie** [comment]
I used the password reset and it worked fine for setting up my initial password... though if that's the way ppl set up their passwords, we'll need to add some instructional text.

**Comment by timwood** [comment]
> we may want to add some text stating that a new account is required even if you've attended previous capitalcamp/gov days before.

Great idea! How about we add this statement to the "Free Ticket" type description? Can you please provide language and I'll add it.
![image](https://cloud.githubusercontent.com/assets/91050/6668982/ee616792-cbcc-11e4-808d-80ccb16d9da4.png)

> the confirmation email came from tim@buchbinder.org - we should probably change that ;)

Good catch! I've changed the site email to drupal4gov@gmail.com. Let me know if it should be something else.

> the confirmation email told me login was the email address i used and the password i set up. however - when i registered, there was no opportunity to create a password.

Password is set after email verification, the one-time password link you used. The email language is purposefully tense-agnostic/vague, "Your password (that you set)", but we can be more explicit there. Please provide suggested language. Also, did you see the instructions/info on the registration thank you page?

**Comment by jdearie** [comment]
How's this:

"Tickets to the event are free, but registration is required. Please register to reserve your ticket. Even if you have attended a Capital Camp or Drupal Government Day event in the past, you will need to register for a new account."

and..

"You will need to set your initial password by going to the login screen and clicking on the Forgot Password? link. You will receive an email with a link to a page that will allow you to update your profile and set your password"

**Comment by jdearie** [comment]
disregard login text. i completely missed it in the original email

**Comment by timwood** [comment]
In the registration email template replace the (that you set) with (that you will set after clicking on the link above).

**Comment by alisonjo315** [comment]
Maybe related -- there's no success message when I save my tickets (via "edit" form).

**Comment by sutch** [comment]
I would expect that the Ticket Registrant is the same as the (recipient of the) Free Ticket.  I suggest the following improvements, ordered by my priority:
- [ ] Rename second section from Free Ticket to Free Ticket Recipient.
- [ ] Add language to top of first section, something like: "Provide information about yourself, the person submitting this registration."
- [ ] Add language to top of second section, something like: "Provide information about the ticket recipient."
- [x] Defaulting second section to use values entered in first section. Possibly use a checkbox or button to trigger the copying of the values. Use language like: "[] Check this box if you are the ticket recipient to use information entered above."

**Comment by timwood** [comment]
@sutch Great suggestions! can you please log these ideas as a new issue and tie to "Post launch" milestone? Also, it would be helpful if you could research how to override the ticket registration form screen you are referring to. I'm sure there is some drupal hook we can use, but I don't know what it is or how to override what is there right now.

**Comment by sutch** [comment]
In the initial email, the following line should be changed from:

> password: Your password (that you set)

to:

> password: Your password (that you will set)

**Comment by timwood** [comment]
@sutch Already fixed. See task description above. We used something a little longer to be even more explicit.

For the language on the ticket page for free ticket I modified it to be:

> Tickets to the event are free, but required. Please register to reserve your ticket. You will create a new account as part of the registration process.
> 
> **A new account is required even if you've attended previous CapitalCamp or Drupal Gov Days before.**

**Comment by sutch** [comment]
@timwood Were the previous username/password lines removed?

> email or username: dsutch@doc.gov
> password: Your password (that you set)

**Comment by timwood** [comment]
What I meant was I just fixed it, pushed up the change, but didn't revert the feature, yet. So you didn't see it when you tried earlier and you still won't see it. But it's in there, available soon.

**Comment by sutch** [comment]
I verified my email address and set a password, but "forgot" to record my password. When I went through the process of requesting an email to reset my password, I still had to enter my current password to reset my password. I believe this was because I was logged in. The only way I could reset my password was to logout and request another password reset.

**Comment by timwood** [comment]
Perchance did you fill in the address field along the way at some point? https://github.com/Drupal4Gov/Drupal-GovCon-2015/issues/59

**Comment by sutch** [comment]
Unsure about the steps.  I am able to replicate (see below).

This may be an issue with COD, rather than an issue specific to our instance.
1. Login
2. Go to the Edit page
3. Forget password and click the _Request new password_ link under the Current password field
   4 Follow instructions and receive the replacement login information email message
4. Use the link found in the email message
5. Click the _Change your password_ link
6. Be presented with a form that requests your current password

**Comment by cmndr-king** [comment]
I am putting the site through its paces on an iPad and was able to register without a problem.  However, I didn't see the information about scholarships. Someone mentioned that there are drop down menus but those do not appear on the iPad so can we make sure that all options show up on the default page for each menu option?

**Comment by cmndr-king** [comment]
Can we replicate the Site Map in the footer? That would help give access points to the various pieces of our site.

**Comment by jonraedeke** [comment]
We should probably add a menu block showing the second level links on main
menu pages with children for people on a touch device that is larger than
the mobile breakpoint.

**Comment by cmndr-king** [comment]
Tim - this is focused on registration so I'm not sure if I can broaden this thread.  I'd love to see if we can provide the option of a personal schedule for attendees.  One, I think it would be helpful to be able to go through our breakouts and mark the ones we're most interested in.  However, more importantly for me, I'd like to use that data to see how popular a session is before the event so that we can move rooms around in advance of the event starting.  My biggest concerns are the training sessions and the coder lounge but it would also be helpful to know what sessions should be moved into the auditorium.  Does COD have this feature by default that we can play with?

**Comment by jdearie** [comment]
There is a My Sessions tab in the user profile. I think users can add a session to their profile to generate that list... 

![image](https://cloud.githubusercontent.com/assets/5174534/6708062/6802515c-cd43-11e4-8695-43d3d9081bda.png)

**Comment by timwood** [comment]
@jdearie Yup, you are right. @cmndr-king Users add sessions to their schedule via a Flag. I haven't seen it in action yet and don't know where it appears, but we can test that.

As for gauging interest from individuals schedules, that will depend on enough users making their schedule, which may not happen. We can make sure the feature works well and promote it. We'll also need to check whether the flag is configured to allow site-wide analysis like that.

**Comment by cmndr-king** [comment]
Thanks!  I’ll poke around and test it out.

-James

---

James King, MLS, FSLA

http://about.me/cmndr_king

**Comment by timwood** [comment]
@jonraedeke Would it be possible to adjust the animation speed in the CSS to accommidate tablets as suggested here: https://www.drupal.org/node/2293041#comment-8923771

**Comment by timwood** [comment]
@jonraedeke Can you make a separate issue for the unfinished issue identified by @cmndr-king so we can close this?

**Comment by jonraedeke** [comment]
Moving concern about second tier menu items on wide touch devices to a separate task.
https://github.com/Drupal4Gov/Drupal-GovCon-2015/issues/78

**Comment by timwood** [comment]
>  Defaulting second section to use values entered in first section. Possibly use a checkbox or button to trigger the copying of the values. Use language like: "[] Check this box if you are the ticket recipient to use information entered above."

This was done in the latest version of COD.
