### ISSUE TITLE
Profile

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2015#55]
- [ ] ~~If it's not too much work, i would recommend adding some instructional text:~~

> "If you do not wish to provide your full location information, please select None from the Country list"

OLD:
When I registered for an account, I checked the box for Government Employee.

After logging in and reviewing my profile, Government Employee was not checked and my t-shirt size selection was not saved.

To update my profile, address fields are required.  Is that really what we want to make people do?

**Comment by timwood** [comment]
Thanks for logging this issue.

I noticed the fact that Govt. employee check, t-shirt size and dietary needs weren't transferring from ticket to user profile sometime this weekend, but didn't do anything about it. :-( It was working before, so not sure what we did to break it. It would be nice if it worked, but at least the values are stored properly with the ticket (I believe), which is the important part.

We fixed the bug with address field being required. Has it come back? When you first hit your user edit screen (profile/password) via the one-time password link (and subsequent visits to the edit screen) the location (address field) should be fully collapsed, no country selected, therefore not be required. Once you select a country, the address field module automatically requires you fill in the address. If you select "- None -" again it should allow you to not fill in address. Do you see this as a major usability issue?

**Comment by jdearie** [comment]
Address field is not required as long as you don't select a country.  So it works as you expected to .... just not as I did as a user :)

If it's not too much work, i would recommend adding some instructional text:

"If you do not wish to provide your full location information, please select None from the Country list"

**Comment by timwood** [comment]
Cancelling this as we had to remove the address field. See https://github.com/Drupal4Gov/Drupal-GovCon-2015/issues/59
