### ISSUE TITLE
Improve 'Attendees' View

### ISSUE THREAD

**Issue by jonraedeke** [Drupal4Gov/Drupal-GovCon-2015#56]
- [x] Configure panel pane in attendees view to use panel path so filters work
- [x] reduce the info output for each attendee. just linked first/last name? 
- [x] output the profile image as "medium" image style

OLD:
@timwood or @alisonjo2786 
Can you test out the Attendees view at /drupal-govcon-2015/community ?
When I try to filter and click 'Apply', it jumps to event landing page. 

Also, could you guys put some filler attendees in there so I can style?

**Comment by alisonjo315** [comment]
I get the same result.  Also, it would be cool if "admin" and "anonymous"
didn't show in the list :-/

I'll add a few more attendees.

**Comment by timwood** [comment]
Wait, I don't see Admin or Anon in the list as a regular user. Also, what do you mean you'll add more attendees? I only see Alison when I view that page. Shoudn't it list all ticket holders?

**Comment by timwood** [comment]
OH! It's the "Show on attendees listing page" checkbox. Only alison's ticket has that checked. Must be defaulted to off. WE need to change that, no?

**Comment by timwood** [comment]
Also, most early registrants didn't fill in first/last name, dietary needs, t-shirt, etc. because these weren't fields on the ticket object then. I think we should ask those folks to go update their ticket.

**Comment by alisonjo315** [comment]
The "show on attendee listing" checkbox isn't on the form when I'm a
regular user.

Also, sorry, I thought Jon needed more registrants so I created more
people... I can clean them up, tho, if it's not helpful.

**Comment by timwood** [comment]
Okay. The "show on attendee listing" field functionality is fixed. I changed the permission, default (to checked) and set the field to required by editing it live on the site here: https://capitalcampstg.prod.acquia-sites.com/ticket_registration/manage/1/fields/field_ticket_attendee_listing

**Comment by alisonjo315** [comment]
Checked by default is fine, but shouldn't make it required -- should allow
ppl not to be "public" or whatever -- or else disable/hide the option
altogether.  (Can't give them an option and then not let them exercise the
option.)

**Comment by timwood** [comment]
Ack! Right you are. With a single on/off checkbox required doesn't work. I've made it not required.

**Comment by jonraedeke** [comment]
If anyone is already editing this view, can they output the profile image as "medium" image style? I'm currently stretching them.

Also, can we reduce the info output below. Maybe just linked first/last name? I would need to the make them very tall to accommodate all the info in case of long titles and orgs.

**Comment by alisonjo315** [comment]
Agreed on trimming info shown as Jon described.

**Comment by timwood** [comment]
Done!

**Comment by jonraedeke** [comment]
My bad, we need to make an image style that is square and assign it to the Attendees view. Let's do 160x160px.

**Comment by jonraedeke** [comment]
Fixed.
