### ISSUE TITLE
BoF Sessions Content

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2015#57]
We have some text for a BoF Sessions informational page. Where should we create that?

**Comment by dsheffler** [comment]
Jess, if you create the page, I'll fit it into the sitemap.

**Comment by jdearie** [comment]
Thx @dsheffler - It's at: /drupal-govcon-2015/bof-sessions

**Comment by dsheffler** [comment]
This has been added to the sitemap.
