### ISSUE TITLE
Show on attendee listing page tweaks

### ISSUE THREAD

**Issue by alisonjo315** [Drupal4Gov/Drupal-GovCon-2015#58]
- [x] "Show on attendee listing page" checkbox not editable by regular users
- [ ] When viewing tickets, "Show on attendee listing page" outputs as "1" (or 0) -- change to "enabled" or "yes" or something.

**Comment by timwood** [comment]
The second item is not that important before launch. Punting.

**Comment by alisonjo315** [comment]
Okay.
