### ISSUE TITLE
Investigate and debug registration issues

### ISSUE THREAD

**Issue by timwood** [Drupal4Gov/Drupal-GovCon-2015#59]
As reported by Danielle, when coming through the one-time login link, if you miss a required field when filling in the form, it comes back and asks you for your current password, which never gets set...

Investigate to try and reproduce.

**Comment by timwood** [comment]
@dsheffler I've confirmed this "bug" with the registration process. ~~I'm not sure whether this is a show stopper. If the user fills in all the required fields, including if they select a country in address, filling out the full address required fields, they will not have a problem.~~

Just kidding. If you select country and even if you fill in all required fields, it still throws a validation error and complains "Your current password is missing or incorrect; it's required to change the Password.". So is this a show stopper? I say it's a pretty big problem. I think the best bet is to remove the address field. Do we really need it for user accounts?

@bendygirl @alisonjo2786 @jonraedeke @jdearie Thoughts?

**Comment by timwood** [comment]
This issue does NOT happen if a different field doesn't validate such as required field "Last Name". I'm removing the address field now.

**Comment by timwood** [comment]
No issues with password when validation errors are thrown due to other required fields being left blank. I've removed the address field.

**Comment by bendygirl** [comment]
Address field wouldn't be necessary. It's not statistics we use and we don't sell a full list, just names and emails. So no need for addresses at all.

**Comment by timwood** [comment]
Thanks! Closing. Speaking of which, we were going to add a note to the registration form about selling the list...https://github.com/Drupal4Gov/Drupal-GovCon-2015/issues/70

**Comment by bendygirl** [comment]
I thought we were going to add that to privacy statement with an opt out on reg? Not sure how far we ever got on how to do that. I remember discussing, but not sure we decided how to do it.
