### ISSUE TITLE
Add Content to Trainings Page

### ISSUE THREAD

**Issue by dsheffler** [Drupal4Gov/Drupal-GovCon-2015#60]
We will need to add content to the trainings page that includes information about the companies as well as the links to Eventbrite. This is not currently ready to add, but we should have a page for the site to include this information in addition to adding the trainings to the schedule that includes the actual sessions, BOFs, etc.

**Comment by timwood** [comment]
Set to April 30th deadline. If that's too late, I can set to March 30.

**Comment by timwood** [comment]
@dsheffler I wasn't on the call Friday, is there enough info to add content to the training page and publish it yet? https://www.drupalgovcon.org/drupal-govcon-2015/trainings

**Comment by timwood** [comment]
@dsheffler Just wanted to highlight this task again. Should I contact Bill B?

**Comment by timwood** [comment]
@dsheffler @bendygirl We need to get the training schedule up. Haven't we confirmed all the training organizations? Can we just put up the page with what they are offering and the cost (free, right?) One user submitted a question about this on the Contact us page. He needs to see what training will be available to he can plan for that.

**Comment by bendygirl** [comment]
I sent the final email to Bill last night for him to send to the trainers, to remind them to create their own eventbrite pages. Once I have their links back and their descriptions, I'll put the content up on trainings. I think I have the content for the Taoti one, they submitted it as a session. @dsheffler can you look at that Taoti submitted session? I am wondering if it's a session and not their bootcamp. I unpublished it thinking it was the bootcamp but I can't see it now and am wondering if I made a mistake.

**Comment by timwood** [comment]
Moving to "print date" milestone. Are trainings almost ready to publish?

**Comment by bendygirl** [comment]
I've got them mostly set up. https://www.drupalgovcon.org/drupal-govcon-2015/full-day-trainings

Karl is adding new images to the page.
