### ISSUE TITLE
Add Volunteer content and form to the site

### ISSUE THREAD

**Issue by dsheffler** [Drupal4Gov/Drupal-GovCon-2015#61]
Could we please add the form (and text that we used last year) to the site, so that we can start getting volunteer requests early?

**Comment by dsheffler** [comment]
Our event would not be able to run smoothly without members of the community such as yourself. Thank you for your interest in volunteering! We have many different volunteer needs, so please fill out the form below with your basic information and volunteer interests. We will provide you with more information a month before the event with your volunteer assignment(s).

The form fields are below:
1. Name:
2. Email address:
3. Phone number:
4. How many days are you available? Please select all that apply.
   1. Prep/setup day, July 21
   2.    Day 1, July 22
   3.    Day 2, July 23
   4.    Day 3, July 24
   5.    All of the above
5.    When are you available? Please select all that apply. [multi-select field]
   1.    July 21, 2 – 5 pm (setup)
   2.    July 22, 7:30 am – noon am
   3.    July 22 afternoon – 5 pm
   4.    July 22, Happy hour - 5pm-8pm
   5.    July 23, 7:30 am – noon am
   6.    July 23 afternoon – 5 pm
   7.     July 24, 7:30 am – noon am
   8.    July 24 afternoon – 5 pm
   9.     July 24, Closing reception 5pm-7pm
6.    How many hours are you available each day?
7.    What would you like to do? Please select all that apply.
   1.    Conference prep (bag stuffing, signage)
   2.    Registration table
   3.    Snack and lunch assistance (no food handling required)
   4.    Room/session monitor
   5.    Session moderator
   6.     Manage speakers’ needs
   7.    Manage vendors’ needs
   8.    Session recorder/IT
   9.      Directions at security
   10.      Traffic cop between sessions
   11.    Happy hour assistance
   12.      Post signage/remove signage
   13.   Conference clean up
   14.    Stage manager for keynotes
   15.    BoF manager
   16.    Training manager
   17.     Drupal BINGO/scavenger hunt
   18.    Other, please specify
8. Comments

**Comment by dsheffler** [comment]
Github changed my numbering around so please ignore that. Also, comments is supposed to be its own field and not under Other, please specify.

**Comment by timwood** [comment]
I fixed the formatting of your comment.

**Comment by Nneka** [comment]
Read the comments in the issue referenced above-->  [Issue #76](https://github.com/Drupal4Gov/Drupal-GovCon-2015/issues/76)  to get an idea of what change is needed.  

Seems as if you'd rather have the ability to attach a webform to a node entity than using the Webform functionality.  Did a little research and found a few modules:

Entityforms
Flexiforms

Will test these two to see how they work.

**Comment by dsheffler** [comment]
I'm just used to being able to create a basic page and add a webform as a block, so it's using both. Not sure if COD has that functionality.

**Comment by timwood** [comment]
@Nneka Out of the box, Webform can be enabled on any content type. My idea in issue #76 is to enable webform on the page content type, export that change as a feature override in one of our two dgc_ features and as a bonus add on the https://www.drupal.org/project/form_builder module to make building the forms awesome.

@dsheffler I'm not sure what you mean adding a webform as a block. As in the Drupal blocks system?

**Comment by dsheffler** [comment]
@timwood, yes. I'm used to being able to check the "use webform as a block" and attach it to any page. I'm not saying that's how it works in COD. :) I just wanted to give an example of how I was thinking the page would look/act.

**Comment by timwood** [comment]
The main reason I think we should use the page content type is that it's OG (and therefore event) aware where the webform content type is not. Just seems like the right thing to do with COD, but maybe I'm wrong.

**Comment by Nneka** [comment]
@timwood  Gotcha!  So going forward, Webforms will be created using the Page content type.  Makes sense to me especially since OG isn't aware of Webforms.  Did you look here to determine that?  (http://capitalcampstg.prod.acquia-sites.com/admin/config/group/permissions/node/event -- making sure I understand).  

Going to feature override adding the webform to the page CT and see what form_builder has to offer.  

Let me know if I'm missing something or there's anything else I need to be aware of.

**Comment by Nneka** [comment]
Doing this on my local dev first...

**Comment by timwood** [comment]
The Webform content type is automatically created by the webform module and COD doesn't do anything to change it, so it doesn't have an organic groups field attached to it, like almost all the other content types in COD. You can enable webform for the page content type at /admin/structure/types/manage/page (last vertical tab "Webform").

**Comment by Nneka** [comment]
@dsheffler After a user fills out the volunteer form, what will the confirmation message say?

**Comment by dsheffler** [comment]
@Nneka, I think something like this would work best: Thank you for your interest in volunteering at Drupal GovCon. Our volunteer team will reach out to you in the coming months regarding assignments.

**Comment by Nneka** [comment]
Volunteering page has been created.  
Check it out....
https://www.drupalgovcon.org/drupal-govcon-2015/volunteering

Currently all fields except Comments is mandatory.  Also wondering if I can find phone number validation.

**Comment by timwood** [comment]
Looks good to me.

**Comment by Nneka** [comment]
Form has been created and is published.

https://www.drupalgovcon.org/drupal-govcon-2015/volunteering

**Comment by Nneka** [comment]
Next question is.. how will users get to the volunteer page?  Where will this link from?

**Comment by dsheffler** [comment]
@Nneka, could we please place it under the Community dropdown? Thanks!

**Comment by jdearie** [comment]
I added the page to the Community drop down menu this morning -  we'll send out some messaging today as well.
