### ISSUE TITLE
Create the Meet the Drupal GovCon team page

### ISSUE THREAD

**Issue by dsheffler** [Drupal4Gov/Drupal-GovCon-2015#62]
We need to create the Meet the Drupal GovCon team page. This page will include the pictures and names, in alphabetical order, of everyone on the organizing committee. Clicking on the picture or name will take the user to an individual profile.

This means that everyone needs to fill out their profile!!!

After site code update:
- [x] Override default panelizer panel for the [DGC team page](https://www.drupalgovcon.org/drupal-govcon-2015/meet-drupal-govcon-team) and add the view content page.
- [x] Flag all organizers ticket registrations with the new "Drupal GovCon Event Organizer" flag.

**Comment by timwood** [comment]
I'd like to create the list of team members as a view, probably using a Flag to securely identify users who are organizers. What fields from the user profile would we like to see on this page and what should it look like? Got any examples from other places online?

**Comment by bendygirl** [comment]
https://portland2013.drupal.org/team.html
http://denver2012.drupal.org/volunteers (I like that it goes to your D.O. profile)
Bad camp "credits" https://2014.badcamp.net/credits

**Comment by jdearie** [comment]
I like having pictures!

**Comment by jamiebeemac** [comment]
## I prefer the Badcamp format. 

Brad

**Comment by timwood** [comment]
Since we aren't ready with content or functionality, I've unpublished the static basic page node.

**Comment by timwood** [comment]
What does everyone think about using the community attendees card styling for the "Meet the team" page? Here's a screenshot of what I've built so far: 

![image](https://cloud.githubusercontent.com/assets/91050/6886642/63245f2c-d612-11e4-919c-29a67d703cda.png)

**Comment by bendygirl** [comment]
I like it.

On Sun, Mar 29, 2015 at 12:52 PM, Tim Wood notifications@github.com wrote:

> What does everyone think about using the community attendees card styling
> for the "Meet the team" page? Here's a screenshot of what I've built so
> far:
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/91050/6886642/63245f2c-d612-11e4-919c-29a67d703cda.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Drupal4Gov/Drupal-GovCon-2015/issues/62#issuecomment-87442868
> .

## 

Kirsten
http://uniongal.blogspot.com
Join Uniongal on Reddit http://www.reddit.com/r/Uniongal/

**Comment by timwood** [comment]
Maybe @jonraedeke can distinguish the same style slightly on this page (red star background) so it differs a little from the community page.

**Comment by timwood** [comment]
And/or perhaps we can make them a little taller to include position and organization like screenshot below. I know @jonraedeke wanted to avoid this on the community page, but maybe it would work here?

![screen shot 2015-03-29 at 1 45 51 pm](https://cloud.githubusercontent.com/assets/91050/6886853/4b862d70-d61a-11e4-8ab9-2fef5376a20c.png)

**Comment by dsheffler** [comment]
This is really, really nice. I'm assuming it might be difficult to have fields by role in COD? I only ask because it would be great to be able to list our roles/what committees we're on. But I'm also not trying to complicate things at all. Just a question...I promise!

**Comment by timwood** [comment]
I've just pushed up the code for this. I decided to leave out the position and organization information until Jon chimes in. I also corrected the sort to be alpha by last name. There is a new flag which applies to the ticket registration object, not the user, so we can have different sets of organizers across events. So an organizer has to obtain a ticket for the associated event, fill in their user profile and then they will show up in the results of this view. 

To flag a ticket for inclusion in the view go to http://SITENAME/ticket_registration/manage/1/registrations, page to the last/second-to-last page, find a few known organizers and click "edit" next to their ticket. On the edit screen check "Flag as event organizer" and click Update.

![screen shot 2015-03-29 at 2 05 42 pm](https://cloud.githubusercontent.com/assets/91050/6886921/b16ff8d4-d61d-11e4-892a-d0d4326e5e49.png)

I realize flagging an individuals ticket registration is a little more complicated than flagging their user account, but it will allow us to have different organizers across different events, year over year.

@dsheffler COD comes with a field level permission module, but let's not complicate it for now. We can improve in the coming months or for next year, depending on time and resources.

**Comment by timwood** [comment]
I've improved on the organizers flag idea by adding "Organizer" below name on the Community attendee list which links to the "meet the Drupal GovCon team" page. On the DGC team page, it doesn't display "Organizer" below the name because everyone on that page is an organizer.
![image](https://cloud.githubusercontent.com/assets/91050/6887323/c36fd610-d629-11e4-9a4a-ca6783f5d63f.png)

@jonraedeke In doing this I was able to use the flag field to output a class in the view row of "Organizer" (case sensitive) which is basically the output label/title of the flag field. Can you use this to style the organizer cards slightly differently?
![image](https://cloud.githubusercontent.com/assets/91050/6887332/f6e560f0-d629-11e4-96f2-dcf418c20259.png)

**Comment by timwood** [comment]
You can now see this live in action in the development environment in Acquia.
http://capitalcampdev.prod.acquia-sites.com/drupal-govcon-2015/meet-drupal-govcon-team

http://capitalcampdev.prod.acquia-sites.com/drupal-govcon-2015/community

**Comment by timwood** [comment]
@Drupal4Gov/members Please let me know whether I missed anyone in the planning team that is registered on the site. Screenshot below is from the live, production site.

> Flag all organizers ticket registrations with the new "Drupal GovCon Event Organizer" flag.

![screen shot 2015-03-29 at 11 34 05 pm](https://cloud.githubusercontent.com/assets/91050/6889796/2529a25e-d66c-11e4-9549-ba5783d9eff4.png)

**Comment by timwood** [comment]
I realized I missed Meagen Williams, Dave Stoline and Annie Stone. I found Annie in the ticket list, but not Dave or Meagen. We'll have to let them know to register so we can add them as organizers.

**Comment by timwood** [comment]
@jonraedeke @onelittlebecca's name is too long and "Organizer" is dropping outside the profile card on the community page. Can you make it one row longer?
![image](https://cloud.githubusercontent.com/assets/91050/6969025/7d701608-d939-11e4-8f40-1d1ff73ecaef.png)

**Comment by onelittlebecca** [comment]
easy fix, i can delete the hyphenated part and roll with goodman. heh :-)

**Comment by jonraedeke** [comment]
@timwood @onelittlebecca I'm sure we'll run into this with others. I'll make it taller.

**Comment by onelittlebecca** [comment]
oh! ok. then i will put it back :-)

**Comment by jonraedeke** [comment]
Committed styling for longer name + Organizer title.
