### ISSUE TITLE
Entity reference autocomplete fields aren't rendering right and don't work?

### ISSUE THREAD

**Issue by timwood** [Drupal4Gov/Drupal-GovCon-2015#65]
From node/add/session speakers field.
![image](https://cloud.githubusercontent.com/assets/91050/6676434/2bf47c1c-cbfe-11e4-8663-74817192d4c2.png)

**Comment by bendygirl** [comment]
it's working everywhere else, just not on session submission.

**Comment by bendygirl** [comment]
also, you can add the name, but you can't see it, it's all the way right and it will show you 1 to 2 letters.

**Comment by jonraedeke** [comment]
Sorry, fixed. These form elements are hard to style. I might need to fine-tune, but now you can at least see what you are doing.
