### ISSUE TITLE
Session Submission - Dev testing

### ISSUE THREAD

**Issue by bendygirl** [Drupal4Gov/Drupal-GovCon-2015#66]
Before we submit an Awesome session, we should make sure you can submit a session and that the session shows up somewhere. I can't perform the steps on Dev. On staging, there seems to be a bug for the autofill, might relate to: "Select the method used to collect autocomplete suggestions. Note that Contains can cause performance issues on sites with thousands of nodes."

We could switch to "starts with" and see if that improves the functionality.

**Comment by bendygirl** [comment]
I was able to add tim and me (me twice?) to the session as speakers, but in Firefox, you can't see who you are adding.

**Comment by timwood** [comment]
See #65 for the speakers field issue.

**Comment by timwood** [comment]
I'm able to submit a session without issue on staging. Please reopen if you still encounter this issue.I'm able to submit a session without issue on staging. Please reopen if you still encounter this issue.
