### ISSUE TITLE
Enhance Register form functionality to reduce data entry

### ISSUE THREAD

**Issue by sutch** [Drupal4Gov/Drupal-GovCon-2015#68]
URL: /ticket/register

Default the second section of the form to use values entered in first section. Possibly use a checkbox or button to trigger the copying of the values. Use language like: "[ ] Check this box if you are the ticket recipient to use information entered above."

**Comment by timwood** [comment]
I feel like COD did this when I was first testing it, but I will need to check on a fresh, clean COD install.

**Comment by sutch** [comment]
The checkbox for using the registering person's information should only be usable on one ticket (recipient) section.

**Comment by timwood** [comment]
Punting this to next year, unless someone else can get to it.

**Comment by timwood** [comment]
COD now comes with this functionality although it's available for more than one ticket and allows you to copy from one to another any direction.

**Comment by timwood** [comment]
Although it doesn't seem to work for email address field. :-(
