### ISSUE TITLE
Something covering forms when validation fails

### ISSUE THREAD

**Issue by timwood** [Drupal4Gov/Drupal-GovCon-2015#69]
I cannot click into any form fields when I submit a form and validation fails (missing required field). Happens on user edit page when registering (maybe on regular edit too) when you erase last name field for example. Encountered in Chrome on Mac.

**Comment by timwood** [comment]
@jonraedeke Seems urgent to me.

**Comment by jonraedeke** [comment]
I'm not able to replicate the issue.

I registered for one ticket and filled out the form for a new user, leaving the last name blank. The form did not validate and showed the warning. I was able to type in the fields and re-submit. Chrome and mac.

Is this still happening for you? Maybe the site was hung up loading?

**Comment by timwood** [comment]
Let's close for now.
