### ISSUE TITLE
Import previous email addresses into mailchimp

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2015#7]

**Comment by timwood** [comment]
Are we still going to do this @jdearie ?

**Comment by timwood** [comment]
@jdearie bueller, bueller, bueller

**Comment by jdearie** [comment]
Need to get the list from @bendygirl 
There are 135 names in the list now, but i believe those are ppl that signed up directly on the drupalgovcon.org site.

**Comment by bendygirl** [comment]
they signed up when we had the splash page up.

On Wed, Apr 1, 2015 at 9:41 AM, Jessica Dearie notifications@github.com
wrote:

> Need to get the list from @bendygirl https://github.com/bendygirl
> There are 135 names in the list now, but i believe those are ppl that
> signed up directly on the drupalgovcon.org site.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Drupal4Gov/Drupal-GovCon-2015/issues/7#issuecomment-88484656
> .

## 

Kirsten
http://uniongal.blogspot.com
Join Uniongal on Reddit http://www.reddit.com/r/Uniongal/

**Comment by timwood** [comment]
@bendygirl do you have the list of users we provided to the coffee sponsor last year? That would be a source of good email accounts without too many spam.

**Comment by bendygirl** [comment]
I'll look for it.

On Wed, Apr 1, 2015 at 9:55 AM, Tim Wood notifications@github.com wrote:

> @bendygirl https://github.com/bendygirl do you have the list of users
> we provided to the coffee sponsor last year? That would be a source of good
> email accounts without too many spam.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Drupal4Gov/Drupal-GovCon-2015/issues/7#issuecomment-88488739
> .

## 

Kirsten
http://uniongal.blogspot.com
Join Uniongal on Reddit http://www.reddit.com/r/Uniongal/

**Comment by jdearie** [comment]
I've imported last year's names into the Drupal GovCon list.  I also created some groups within the list (attendee,  volunteer, speaker, organizer).  The groups should allow us to send more targeted messages.

**Comment by timwood** [comment]
Awesome!
