### ISSUE TITLE
Add note somewhere about attendee list being sold

### ISSUE THREAD

**Issue by timwood** [Drupal4Gov/Drupal-GovCon-2015#70]
@bendygirl @dsheffler @jdearie Do we have any language for this? If not, please provide. I think it should go into the "Free ticket" description which is shown on the initial ticket/register screen.

**Comment by timwood** [comment]
@bendygirl Also mentioned we decided this should be in the privacy policy and there should be a checkbox to opt out on registration. Should we add this now that registrations have already started?

**Comment by bendygirl** [comment]
Not sure that's actually what we decided.

I can work on the privacy policy today. But we would need an opt out
button. But I was out during December and I thought you all might have
discussed it then. I was thinking someone mentioned opt in. So, I'm not
positive I'm right on this. Did we ever come to a decision on this one?

On Wed, Mar 18, 2015 at 8:52 AM, Tim Wood notifications@github.com wrote:

> @bendygirl https://github.com/bendygirl Also mentioned we decided this
> should be in the privacy policy and there should be a checkbox to opt out
> on registration. Should we add this now that registrations have already
> started?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Drupal4Gov/Drupal-GovCon-2015/issues/70#issuecomment-82955508
> .

## 

Kirsten
http://uniongal.blogspot.com
Join Uniongal on Reddit http://www.reddit.com/r/Uniongal/

**Comment by dsheffler** [comment]
For Canspam laws, we have to provide an opt out or an opt in. If we don't
want people to hate us, I would suggest an opt-in.

**Comment by timwood** [comment]
The Canspam laws would apply to the mailing list solution. Mailchimp provides this for the list we are managing now and whichever company buys the list will likely use a solution that provides similar functionality. So it's not a requirement in that way. Can one of you send this to the broader list via email as a decision point by X deadline?

**Comment by bendygirl** [comment]
Good idea Tim. Will do that now.

On Wed, Mar 18, 2015 at 9:37 AM, Tim Wood notifications@github.com wrote:

> The Canspam laws would apply to the mailing list solution. Mailchimp
> provides this for the list we are managing now and whichever company buys
> the list will likely use a solution that provides similar functionality. So
> it's not a requirement in that way. Can one of you send this to the broader
> list via email as a decision point by X deadline?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Drupal4Gov/Drupal-GovCon-2015/issues/70#issuecomment-82975155
> .

## 

Kirsten
http://uniongal.blogspot.com
Join Uniongal on Reddit http://www.reddit.com/r/Uniongal/

**Comment by dsheffler** [comment]
Could we please not continue making design by committee decisions? We
decided to make smaller committees so we would avoid having too many people
weighing in. Can the three of us just decide this, please?

**Comment by bendygirl** [comment]
I don't think I'd have been on that committee. I was just noting i remember
this discussed.

Perhaps the web team?

I still think a decision was made, I am not sure we even need to make
another one.

I asked Nina, she remembers we made a decision on this too, just don't
remember when. So, I am not crazy. Either we ask, or look through the
meting notes until we find it. I feel like it was this fall.

On Wed, Mar 18, 2015 at 9:43 AM, dsheffler notifications@github.com wrote:

> Could we please not continue making design by committee decisions? We
> decided to make smaller committees so we would avoid having too many people
> weighing in. Can the three of us just decide this, please?
> 
> On Wed, Mar 18, 2015 at 9:38 AM, Kirsten notifications@github.com wrote:
> 
> > Good idea Tim. Will do that now.
> > 
> > On Wed, Mar 18, 2015 at 9:37 AM, Tim Wood notifications@github.com
> > wrote:
> > 
> > > The Canspam laws would apply to the mailing list solution. Mailchimp
> > > provides this for the list we are managing now and whichever company
> > > buys
> > > the list will likely use a solution that provides similar
> > > functionality.
> > > So
> > > it's not a requirement in that way. Can one of you send this to the
> > > broader
> > > list via email as a decision point by X deadline?
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/Drupal4Gov/Drupal-GovCon-2015/issues/70#issuecomment-82975155
> > 
> > > .
> > 
> > ## 
> > 
> > Kirsten
> > http://uniongal.blogspot.com
> > Join Uniongal on Reddit http://www.reddit.com/r/Uniongal/
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/Drupal4Gov/Drupal-GovCon-2015/issues/70#issuecomment-82975591
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Drupal4Gov/Drupal-GovCon-2015/issues/70#issuecomment-82977292
> .

## 

Kirsten
http://uniongal.blogspot.com
Join Uniongal on Reddit http://www.reddit.com/r/Uniongal/

**Comment by timwood** [comment]
There is a note at the top of this meeting notes from September (search for opt-out). https://docs.google.com/a/buchbinder.org/document/d/1-91sR3XP3KwHuvGYs1HThfAeck0jZQyfsMzG4gjKt9Q/edit

> On registration form mention your info (signing a release form) is being sold to one of the sponsors. Offer option to opt-out during registration and afterward.

Right above that is also this comment to help figure out how much food to buy. We also did not implement this. Is it possible there are other website suggestions that got lost in meeting notes?

> on the website: add a form that allows people to choose how many days/which days they will be attending the event to help with how much food is bought.

**Comment by bendygirl** [comment]
Looks like we dropped the ball on this. Any thoughts on what we do now?

**Comment by dsheffler** [comment]
Any reason why we can't just update the form and then send an email to
attendees asking them to update their info? That being said, someone should
go through past meeting minutes as Tim suggested and make sure nothing else
is missing.

---

Working to find a cure for blood cancers. Donate and save a life! -
http://pages.teamintraining.org/nca/yourway15/dsheffler

**Comment by bendygirl** [comment]
Just need to find someone who has the time to write this up. I'm sure we could use a privacy statement from another site. We should probably have a code of conduct, too.

**Comment by dsheffler** [comment]
Becca already wrote a code of conduct and it's live on the site (under the
About menu). A privacy statement should be fairly easy to lift from another
Drupal camp that does the same thing.

---

Working to find a cure for blood cancers. Donate and save a life! -
http://pages.teamintraining.org/nca/yourway15/dsheffler

**Comment by bendygirl** [comment]
I like the borrowing from another site.

**Comment by timwood** [comment]
This issue was moved to Drupal4Gov/Drupal-GovCon-2016#26
