### ISSUE TITLE
Sponsor logo hyperlinks broken

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2015#71]
All of the logos for sponsors link to:

https://www.drupalgovcon.org/%5Bfield_sponsor_url%5D

**Comment by timwood** [comment]
Fixed yesterday. This has to do with the fact that we've overridden the sponsors view, added a field, reconfigured field rewrites and reordered fields. When the features are reset the view loses field order and needs to be reordered.
