### ISSUE TITLE
Create Contact Us page

### ISSUE THREAD

**Issue by dsheffler** [Drupal4Gov/Drupal-GovCon-2015#75]
Please create a contact us page similar to what is on the Drupalcon LA site: https://events.drupal.org/losangeles2015/contact

Our inquiries dropdown should include General Questions, Scholarships, Sessions, Sponsorships, and Volunteering

**Comment by jdearie** [comment]
I created the webform and added it to the main menu... but it doesn't show up unless I'm logged in.

Did I miss a step?

https://www.drupalgovcon.org/drupal-govcon-2015/contact-us

**Comment by jdearie** [comment]
Never mind - figured it out.  I moved Contact Us menu item to be listed before Manage Conference and it magically appears. Email notifications of submissions go to drupal4gov@gmail.com

**Comment by timwood** [comment]
I tweaked the form to include defaults for first and last name using tokens from user profile. [current-user:field_profile_first] [current-user:field_profile_last]
