### ISSUE TITLE
Make second tier of main menu visible on wide touch devices

### ISSUE THREAD

**Issue by jonraedeke** [Drupal4Gov/Drupal-GovCon-2015#78]
The switch from menu button to horizontal menu with hover drop-downs occurs at 44em(704px). Many touch devices are wider. They can't hover to see second level.

Options
- Show the drop-down on touch briefly before going to destination to give users a chance to tap on another item
- Show drop-down on first tap and require another tap to go to location
- Use modernizr to test for touch and use the menu button for all touch users

**Comment by timwood** [comment]
@jonraedeke Any interest in working on this?

**Comment by jonraedeke** [comment]
Yep, still working on this one. Thanks for checking.

**Comment by jonraedeke** [comment]
Here's the solution I came up with:
Detect touch events with Modernizr and repurpose the mobile menu for touch devices. Committed the styling and Modernizr module, enabled with dgc_deploy.

**Comment by jonraedeke** [comment]
![screen shot 2015-04-22 at 11 02 32 pm](https://cloud.githubusercontent.com/assets/2054715/7311220/398932d8-ea07-11e4-8a10-9bf0f9f183c8.png)

![touch_menu](https://cloud.githubusercontent.com/assets/2054715/7311226/44633e60-ea07-11e4-9a0e-f8a45adaee64.png)

**Comment by timwood** [comment]
Great solution. Thanks.
