### ISSUE TITLE
Update COD to 7.x-1.0-beta8 

### ISSUE THREAD

**Issue by jonraedeke** [Drupal4Gov/Drupal-GovCon-2015#79]
Panopoly has good documentation on the steps for upgrading a Drupal distro. 
https://www.drupal.org/node/2272177
1. drush dl cod
2. drush up drupal
3. drush cc all
4. drush fra -y

**Comment by timwood** [comment]
Oh poop.

**Comment by timwood** [comment]
Working on a patch as a result of this update to contribute here: https://www.drupal.org/node/2458819

**Comment by timwood** [comment]
Upgrade is now done in Git. I'm testing on acquia dev environment with fresh copy of prod DB/files now.

**Comment by timwood** [comment]
Looks good! Now to move onto more important stuff... @jonraedeke Let me know if you run into trouble in your environment.
