### ISSUE TITLE
Set sessions to automatically be published, display in list and engageable

### ISSUE THREAD

**Issue by timwood** [Drupal4Gov/Drupal-GovCon-2015#81]
- [x] Change default published setting in ctype to published
- [x] Investigate and possibly modify COD session view(s)
  - [x] Proposed session list vs. accepted vs. ?
  - [x] Contextually filter session view by session track term name
  - [x] Make session rows output purdy
  - [x] Search by title or keyword (views combined filter or search?)
- [x] Ensure comments are open by default and allowed by authenticated user
- [x] Add comment form and comments to session panel
- ~~~Voting on sessions?~~~ <-- consensus is we don't need user voting
- [x] Publish all sessions live on site and enable comments

Post code update:
- [x] Update program page (/drupal-govcon-2015/upcoming_program) to include link to proposed sessions view
- [x] Add Proposed Sessions menu item (/drupal-govcon-2015/sessions) under Program main menu item
- [x]  Set all published sessions to new status of "Proposed"

**Comment by timwood** [comment]
> Voting on sessions?

@dsheffler Do we also need to look into user voting on sessions? I think COD comes with something OOTB for this. Not sure whether it's intended for participants or only for planners/schedulers.

**Comment by timwood** [comment]
Someone overrode the feature on the production website to publish sessions automatically. Repeat and export feature override. Feature: cod_session

**Comment by timwood** [comment]
Comments wasn't being output by the session panel included with COD.

**Comment by timwood** [comment]
>  Publish all sessions live on site and enable comments

Kirsten says she'll do this piece.

**Comment by timwood** [comment]
@jonraedeke Please have a look at the view I've made and make it purdy. You can see it in a local copy or the Acquia dev environment at http://HOSTNAME/drupal-govcon-2015/sessions (you need to change the status of some sessions to "Proposed" or "Accepted". If accepted append /accepted to the view. The view is grouped by session track and filterable by that with the last argument. Eg. http://HOSTNAME/drupal-govcon-2015/sessions/proposed/business-and-strategy

I didn't get to the session tracks view/summary to add to the top like on DrupalConSF

> Make session rows output purdy

**Comment by dsheffler** [comment]
@timwood, the session track descriptions are as follows:

Code and DevOps
This track is focused on developers and the back-end technologies to deal with today’s and future challenges. With the coming release of Drupal 8, as well as emerging Web technologies, preparation is essential. These sessions will help you learn how to deliver effective solutions to meet these needs.

Business and Strategy
The purpose of this track is two-fold - one angle helps you to understand the advantages of Drupal from an organizational leadership angle and the other is to highlight the great Drupal sites and projects you're working on and to show what's possible. These sessions are business focused, and will be non-technical.

Site Building
Learn how to leverage the flexibility of Drupal to deliver experiences in nearly limitless ways. See how you are able to do this—often without code and relying on the ever-expanding universe of contributed modules.

Front End, UX & Design
This track covers delivering projects focused on the most important audience—the end user. Learn how to leverage Drupal to help you keep abreast of emerging trends in the mobile, componentized Web world. We’ll show you strategies for fostering collaboration between content creators, designers, strategists, and end-users.

Training
These all-day trainings focus on making your team successful in Drupal. As anyone in the field knows, finding knowledgeable practitioners and getting good training is challenging. Here, we show how to bring team members up to speed in Drupal, and where and how to look for outside assistance when internal resources are scant.

**Comment by timwood** [comment]
Thanks @dsheffler Karl for getting the session track descriptions written. I've added these to the live site. For now they appear on session pages to the right, under the track title.
![screen shot 2015-03-29 at 2 52 57 pm](https://cloud.githubusercontent.com/assets/91050/6887125/8b35b3c4-d623-11e4-9fb2-12859161bd78.png)

And there is a taxonomy page for each, which we may replace/redirect elsewhere as part of this task to improve session listings.
![screen shot 2015-03-29 at 2 53 56 pm](https://cloud.githubusercontent.com/assets/91050/6887131/b7e6a612-d623-11e4-96cb-5e9204f6b7e7.png)

**Comment by timwood** [comment]
The session tracks now appear above the new session view.

**Comment by jonraedeke** [comment]
Thanks @timwood! I got a start on styling. I haven't added the icons yet, but those will go on the left of each track link. Heads up, you'll need to pull and revert dgc_deploy since I added a few classes to the view.

**Comment by timwood** [comment]
Looks awesome so far, Jon. What do you have planned for the session description? Can we do the roll-over idea by adding the description to the attached view? Or do you have some other idea?

**Comment by dsheffler** [comment]
Is it ok to disable the Proposed Sessions menu item until the styling is done for that page? Without proper spacing and theming, it's honestly a bit difficult to read.

Edit: I've disabled the menu item. We can add back in once @jonraedeke has had a chance to style the page.

**Comment by dsheffler** [comment]
Just an FYI that the page I'm referring to is https://www.drupalgovcon.org/drupal-govcon-2015/sessions.

**Comment by timwood** [comment]
I'm for leaving up the menu item. I think the page is more useful than no page.

**Comment by timwood** [comment]
I've pushed up @jonraedeke 's initial styling for the sessions section and re-enabled the Proposed Sessions link in the main menu. https://www.drupalgovcon.org/drupal-govcon-2015/sessions

FYI, when sessions close and we have changed sessions to "Accepted" status we can change the main menu link to point to https://www.drupalgovcon.org/drupal-govcon-2015/sessions/accepted.

**Comment by timwood** [comment]
@jonraedeke Noticed one bug. If you filter away all results in the sessions view, the no results text shows but is up by the track filter buttons, actually under it. Can you fix this when you work on it next?

![image](https://cloud.githubusercontent.com/assets/91050/6943857/a9521b62-d85e-11e4-895c-1b7a5e0439d6.png)

**Comment by jonraedeke** [comment]
Just pushed the styling that includes the session track icons. @timwood I also fixed the empty view result styling bug.

![screen shot 2015-04-01 at 11 19 47 pm](https://cloud.githubusercontent.com/assets/2054715/6957185/f4b96430-d8c6-11e4-90b6-d4c789d5a3c3.png)

**Comment by charlieartist** [comment]
Thanks, Jon. What color will the speaker track be? These look good so far, as well as pop is concerned.

**Comment by jonraedeke** [comment]
@charlieartist Here's png icons for reference (the site used svg). For the buttons on hover and active, the icons will be on white, so they will pop even more.

![building](https://cloud.githubusercontent.com/assets/2054715/6964092/0d63eaa8-d914-11e4-8ee4-f0339f48a4c4.png)
![business](https://cloud.githubusercontent.com/assets/2054715/6964095/0d663808-d914-11e4-9db8-542739da4ba5.png)
![devops](https://cloud.githubusercontent.com/assets/2054715/6964090/0d6202c4-d914-11e4-8a19-668c5193e822.png)
![keynote](https://cloud.githubusercontent.com/assets/2054715/6964094/0d64f9b6-d914-11e4-9890-62a9d4f333e4.png)
![training](https://cloud.githubusercontent.com/assets/2054715/6964091/0d63dd10-d914-11e4-8cf7-71a589f15a62.png)
![ux](https://cloud.githubusercontent.com/assets/2054715/6964093/0d6407e0-d914-11e4-97b9-68268cb09296.png)

**Comment by jonraedeke** [comment]
@timwood If you have time, can you fix the attached view for selecting session track so it doesn't output an empty div for 'none'. If not, I can try to style away the space it creates at the top of the list.

**Comment by timwood** [comment]
Something caused the breadcrumbs to get all screwy. I don't see anything obvious changes to the view in the git commits. HEre is a screenshot of what I'm seeing locally.

![image](https://cloud.githubusercontent.com/assets/91050/6967252/25c0608c-d92c-11e4-8cb1-caf69d26483c.png)

**Comment by timwood** [comment]
I cannot reproduce the breadcrumb issue in Acquia dev environment on the latest develop branch. Even after copying DB from prod. Not going to worry about it for now.

**Comment by timwood** [comment]
@jonraedeke Enabling the "hide if empty" setting under no results behavior for the session track field removed the empty nested divs inside the first row result, but didn't get rid of the entire row. With the contents of the first row div gone the extra space seems to be gone too. I still don't understand why it's showing that empty row to begin with.

![image](https://cloud.githubusercontent.com/assets/91050/6968724/d8174f66-d936-11e4-98d0-20fcaf9ca305.png)

**Comment by jonraedeke** [comment]
@timwood Thanks! I think it's fine.
