### ISSUE TITLE
Style Twitter page with nice image and properly sized logo

### ISSUE THREAD

**Issue by timwood** [Drupal4Gov/Drupal-GovCon-2015#9]
https://twitter.com/drupalgovcon

**Comment by jonraedeke** [comment]
Can you remind me what the login for twitter is? Chat is fine.

Here is the logo in a square, but I'd like to also style the colors of the Twitter page.
![drupal_govcon_logo_square](https://cloud.githubusercontent.com/assets/2054715/5738109/6104eb76-9bb6-11e4-838c-245a376a3c69.png)

**Comment by timwood** [comment]
Any progress @jonraedeke or should I go ahead and put up the square image for now?

**Comment by jonraedeke** [comment]
Sorry, I just updated the logo and changed the header color. It's good
enough for now, but I'll think up some kind of cool bg images or something.

**Comment by timwood** [comment]
No need to be sorry. Thanks for working on it! Feel free to close this or leave it open for the background image bit.
