### ISSUE TITLE
Unable to edit track after submitting session

### ISSUE THREAD

**Issue by dsheffler** [Drupal4Gov/Drupal-GovCon-2015#90]
We received an email that someone was unable to edit the track for the session they submitted. I went to go in to edit the track, and I was missing the functionality as well. I am an admin. We should at least allow administrators to alter the tracks for the session, since we may need to make adjustments during session selection too.

**Comment by jdearie** [comment]
It appears that the edit mode doesn't include a track field at all.... it's not there to be able to modify.

**Comment by alisonjo315** [comment]
I'm looking into it.

In the meantime are there any sessions' session tracks you need edited sooner than later?  If so, please send links. ( @jdearie @dsheffler )

**Comment by timwood** [comment]
I see a session track field on a few sessions I tested editing. I was testing as Drupal super admin. Wonder why you weren't able to see the field @jdearie. Maybe group membership issue.

**Comment by timwood** [comment]
![screenshot_2015-04-10-16-58-22](https://cloud.githubusercontent.com/assets/91050/7097405/4d479fbc-dfa3-11e4-8140-977f0193c2ae.png)

![screenshot_2015-04-10-16-58-35](https://cloud.githubusercontent.com/assets/91050/7097398/39da2152-dfa3-11e4-8ce6-d1e97d2ebb56.png)

**Comment by dsheffler** [comment]
It seems that only Super Admins have the ability to edit tracks.

**Comment by alisonjo315** [comment]
Indeed -- only user 1 can edit this field, not even the rest of admin users.  I was just checking to see if any other fields are affected like this, just hadn't updated the issue yet, sorry.

**Comment by dsheffler** [comment]
@alisonjo2786, we need to edit https://www.drupalgovcon.org/drupal-govcon-2015/sessions/extending-your-agencys-reach-drupal-extranet to be in the Business and Strategy track. I can't tell right now if it is or not! The other one is https://www.drupalgovcon.org/drupal-govcon-2015/sessions/drupal-7-taxonomies-and-faceted-search-api-0. It should be listed in Site Building. Thanks!

**Comment by alisonjo315** [comment]
It's got to be something with OG -- the session track field is an entity reference field that targets an OG vocab (the machine name is og_vocabulary, no field_, so it must have come with COD or the OG vocab module or something like that).

Furthermore, we all know OG effs up your perms for no reason every chance it gets.

Still digging, just sharing.

**Comment by alisonjo315** [comment]
@dsheffler Done!  Those two sessions actually had _no_ track selected.

(At first I was like, what the WHAT?! why isn't that a required field?! but then I thought, that actually makes sense -- I can see someone being like, "I'm not really sure, maybe I'm also new, so I'll let you put it where you want it.")

**Comment by timwood** [comment]
I noticed another without a track. https://www.drupalgovcon.org/drupal-govcon-2015/sessions/paraphrasing-panels-panelizer-and-panopoly/edit

I added it to Site Building.

**Comment by timwood** [comment]
Turns out we have quite a few (35+) without a selected session track. Now I'm wondering whether we should require this field...

**Comment by timwood** [comment]
Tried adding "Session organizer" role to regular user. No luck.

**Comment by timwood** [comment]
Adding a regular user as a member to the organic group for the event enabled them to edit the session track field.  So the solution is to add all admins as members in the OG. This can be done at https://www.drupalgovcon.org/group/node/1/admin/people/add-user. I've added everyone that was a site Admin to the group.

**Comment by timwood** [comment]
As for the original session author being able to change their own session track, I guess for now that cannot be done.

**Comment by timwood** [comment]
So with 35+ sessions without a track, what does everyone think about requiring the session track field? This can be done at https://www.drupalgovcon.org/admin/structure/taxonomy/session_tracks_1/edit under "Node - Session".

**Comment by timwood** [comment]
Or can be done at https://www.drupalgovcon.org/admin/structure/types/manage/session/fields/og_vocabulary

**Comment by alisonjo315** [comment]
I shared my opinion on that already, but I don't feel strongly either way,
so whatevs :)

(I'd go with whatever's less annoying for us -- dealing with "non-tracked"
sessions, or dealing with "poorly-tracked" sessions -- right now it seems
like non-tracked is more annoying, but if ppl do a poor job putting their
sessions in tracks, would we allow ourselves to just move them, or would we
want to contact each person to get their consent?  B/c that would be way
more annoying and time-consuming.)

**Comment by dsheffler** [comment]
We need sessions in tracks for session selection. I think it's easiest for us to choose.

**Comment by timwood** [comment]
Okay. We'll leave it as a not required field and let site admins categorize sessions that are submitted without track.

**Comment by dsheffler** [comment]
Could we have it as both and not have it affect the past submissions? I'd
like to make it easier on us if possible to not have to pick categories for
the future ones.

---

Working to find a cure for blood cancers. Donate and save a life! -
http://pages.teamintraining.org/nca/yourway15/dsheffler

**Comment by timwood** [comment]
If we set it as a required field now, it will affect any future session submissions as well as any sessions without a track selected. Meaning those session owners will probably not be able to edit their sessions until we (an admin) can add a session track to them.

**Comment by dsheffler** [comment]
I thought Kirsten was taking care of that soon, which is why I suggested
it. Hopefully not too many people are editing their sessions for it to be
causing an issue.

---

Working to find a cure for blood cancers. Donate and save a life! -
http://pages.teamintraining.org/nca/yourway15/dsheffler

**Comment by alisonjo315** [comment]
Danielle what do you mean "have it as both"?

**Comment by dsheffler** [comment]
Meaning that the field is required for future submissions and that users can't edit their previous submissions until there is a track assigned to them. It sounds like this might be a non-issue since Kirsten already edited the submissions.

**Comment by alisonjo315** [comment]
Ok. I don't understand, why does it matter if users edit their submissions
before their sessions have a track assigned to them?  (Yes Kirsten finished
all but a handful yesterday.)

**Comment by timwood** [comment]
@alisonjo2786 I think the worry about users editing their submissions if there was no track previously selected is that they wouldn't be able to edit the node once we require a field, which they cannot change.

**Comment by timwood** [comment]
Since all previously submitted sessions are now categorized (thanks @bendygirl!), I've set the session track field to required. I tested submitting a session as a regular user and also editing it afterward. All works, except as we already knew, I cannot change the session track due to weird OG permissions.
