### ISSUE TITLE
dgc_sessions view, sorting

### ISSUE THREAD

**Issue by alisonjo315** [Drupal4Gov/Drupal-GovCon-2015#92]
Currently there's no sorting set -- but we have "group by session track," so, need to sort first by session track then maybe by date or NID or alpha-title or something (IMO, anyway -- i think the way it's grouping now is awkward).
https://www.drupalgovcon.org/drupal-govcon-2015/sessions

**Comment by timwood** [comment]
Agreed about awkwardness of the sort. Sorry for missing this when I built it. Personally, I think we should probably just get rid of pagination.

**Comment by alisonjo315** [comment]
Okay, but that would be in addition to changing the sort -- feel free to modify the issue.

**Comment by timwood** [comment]
The grouping already does the sort by session track when there is no pagination. With no other sort defined Drupal defaults to post date I believe, which I think is a reasonable sort choice.

**Comment by timwood** [comment]
Pagination removed from view. Jon has made it looks good and not too long by laying out in a grid.
![image](https://cloud.githubusercontent.com/assets/91050/7106142/46bef834-e106-11e4-974a-82486b3150f0.png)
