### ISSUE TITLE
Remove extra space on initial ticket registration page

### ISSUE THREAD

**Issue by timwood** [Drupal4Gov/Drupal-GovCon-2015#95]
A 300px height was added to .container.preface in commit 30ffcb48585b6fadf53cc28ca10ae0652ce61107 (git diff b33630eeb4e4f014454e53aae0752aefe2c5c556..30ffcb48585b6fadf53cc28ca10ae0652ce61107 docroot/sites/all/themes/govcon/sass/govcon.styles.scss) that is affecting the initial ticket registration page. Just need to adjust the css targeting, I think.

![screen shot 2015-05-04 at 9 48 02 pm](https://cloud.githubusercontent.com/assets/91050/7465937/27ffb7a4-f2a8-11e4-89e1-4fe7b0338a55.png)

**Comment by jonraedeke** [comment]
Fixed
