### ISSUE TITLE
Add humans.txt to site

### ISSUE THREAD

**Issue by timwood** [Drupal4Gov/Drupal-GovCon-2015#99]
http://humanstxt.org/

Why? Because it's fun!

**Comment by timwood** [comment]
Per @sutch suggestion we should include ASCII photos of ourselves in the contents!

**Comment by alisonjo315** [comment]
Yes!!!!

++++1

**Comment by timwood** [comment]
Done. Contains Tim and Jon credit with ASCII photos of each, for now.

**Comment by alisonjo315** [comment]
​Love it!!!!!!!  (Tim's image is probably too big, though -- you can't
really see the whole thing on your screen at once like you can with Jon's.)

**Comment by timwood** [comment]
Yeah. I didn't want to spend too much time on it. I just need to resize the original image to get a smaller version because the resize feature of the image to ascii tool I was using didn't work.
